// @ts-check
import * as THREE from 'three';

export class ThermalVisionSystem {
  /** @param {THREE.Scene} scene @param {import('../effects/CaveFog.js').CaveFog} fog @param {import('../core/EventBus.js').EventBus} events @param {import('../core/Settings.js').Settings} settings @param {import('../world/CaveWorld.js').CaveWorld} world */
  constructor(scene,fog,events,settings,world){this.scene=scene;this.fog=fog;this.events=events;this.settings=settings;this.world=world;this.spatial=world.spatial;this.active=false;this.adaptation=0;this.afterimage=0;this.sampleTimer=0;this.cursor=0;this.lastUpdateMs=0;this.tempMatrix=new THREE.Matrix4();this.tempScale=new THREE.Vector3();this.tempColor=new THREE.Color();this.tempPosition=new THREE.Vector3();this.identityQuaternion=new THREE.Quaternion();this.buildTrailPool();}

  buildTrailPool(){const capacity=112;const geometry=new THREE.SphereGeometry(.12,6,4);const material=new THREE.MeshBasicMaterial({color:0xffffff,vertexColors:true,transparent:true,opacity:.34,depthWrite:false,depthTest:true,blending:THREE.AdditiveBlending,fog:true});this.trailMesh=new THREE.InstancedMesh(geometry,material,capacity);this.trailMesh.frustumCulled=false;this.trailMesh.visible=false;this.scene.add(this.trailMesh);this.trails=Array.from({length:capacity},()=>({active:false,position:new THREE.Vector3(),velocity:new THREE.Vector3(),age:0,life:.5,temperature:.8}));}

  toggle(){this.setActive(!this.active);}
  setActive(active){if(this.active===active)return;this.active=active;if(active)this.afterimage=1;document.body.classList.toggle('thermal',active);this.events.emit('thermal-changed',{active});}

  /** @param {import('../entities/bat/BatAgent.js').BatAgent[]} agents @param {THREE.Camera} camera @param {import('../entities/snake/SnakeController.js').SnakeController} controller */
  sample(agents,camera,controller){if(!this.active)return;const profile=this.settings.profile(),capacity=profile.thermalTrails;if(capacity<=0)return;let emitted=0;for(const bat of agents){if(!bat.active||bat.velocity.lengthSq()<55||!this.spatial.hasLineOfSight(camera.position,bat.position))continue;this.tempPosition.subVectors(bat.position,controller.headPosition).normalize();const aim=Math.max(0,this.tempPosition.dot(controller.direction));const charged=controller.strike.state==='prepare'?controller.strike.charge*aim:0;const slot=this.trails[this.cursor++%capacity];slot.active=true;slot.position.copy(bat.position);slot.velocity.copy(bat.velocity);slot.age=0;slot.life=profile.thermalTrailLife*(1+charged*.42);slot.temperature=THREE.MathUtils.clamp(.66+bat.panic*.2+charged*.12,0,1);emitted+=1;if(emitted>=(this.settings.get('quality')==='high'?4:2))break;}}

  /** @param {number} dt @param {import('../entities/bat/BatAgent.js').BatAgent[]} agents @param {THREE.Camera} camera @param {import('../entities/snake/SnakeController.js').SnakeController} controller */
  update(dt,agents=[],camera=null,controller=null){const started=performance.now();const reduced=this.settings.get('reducedFlashing');const target=this.active?1:0;const speed=this.active?(reduced?1.7:3.3):2.25;this.adaptation+=(target-this.adaptation)*Math.min(1,dt*speed);if(!this.active)this.afterimage=Math.max(0,this.afterimage-dt*1.7);else this.afterimage=1;this.fog.setThermalBlend(this.adaptation);this.world.materials.setThermalBlend(this.adaptation);this.world.lighting.setThermalBlend(this.adaptation);this.sampleTimer-=dt;if(this.active&&agents.length&&camera&&controller&&this.sampleTimer<=0){this.sampleTimer=this.settings.get('quality')==='high' ? .055 : .11;this.sample(agents,camera,controller);}this.applyEmitterAdaptation();this.updateTrails(dt);this.lastUpdateMs=performance.now()-started;}

  applyEmitterAdaptation(){const intensity=this.settings.get('sensoryIntensity');this.scene.traverse((object)=>{if(!object.userData.heat)return;const kind=object.userData.heatKind;const threshold=kind==='head'||kind==='snakeHead' ? 0 : kind==='torso'||kind==='wingRoot' ? .08 : kind==='snakeBody' ? .16 : .24;const clarity=THREE.MathUtils.smoothstep(this.adaptation,threshold,Math.min(1,threshold+.42));object.visible=clarity>.01||this.afterimage>.01;if(object.material&&'opacity'in object.material)object.material.opacity=(object.userData.baseOpacity??1)*Math.max(clarity,this.afterimage*(this.active?0:.16))*intensity;});}

  updateTrails(dt){const limit=this.settings.profile().thermalTrails;let visible=this.adaptation>.02||this.afterimage>.02;for(let index=0;index<this.trails.length;index++){const trail=this.trails[index];if(index>=limit||!trail.active){this.tempMatrix.makeScale(0,0,0);this.trailMesh.setMatrixAt(index,this.tempMatrix);continue;}trail.age+=dt;if(trail.age>=trail.life){trail.active=false;this.tempMatrix.makeScale(0,0,0);this.trailMesh.setMatrixAt(index,this.tempMatrix);continue;}const fade=1-trail.age/trail.life;this.tempPosition.copy(trail.position).addScaledVector(trail.velocity,-trail.age*.045);this.tempScale.set(.28+trail.velocity.length()*.018,.18,.32+trail.velocity.length()*.025).multiplyScalar(fade);this.tempMatrix.compose(this.tempPosition,this.identityQuaternion,this.tempScale);this.trailMesh.setMatrixAt(index,this.tempMatrix);this.trailMesh.setColorAt(index,this.tempColor.setRGB(fade*trail.temperature,fade*.22,fade*.04));}this.trailMesh.visible=visible;this.trailMesh.material.opacity=.28*this.settings.get('sensoryIntensity')*Math.max(this.adaptation,this.afterimage*.2);this.trailMesh.instanceMatrix.needsUpdate=true;if(this.trailMesh.instanceColor)this.trailMesh.instanceColor.needsUpdate=true;}

  dispose(){this.active=false;this.adaptation=0;this.afterimage=0;this.fog.setThermalBlend(0);this.world.materials.setThermalBlend(0);this.world.lighting.setThermalBlend(0);document.body.classList.remove('thermal');this.scene.traverse((object)=>{if(object.userData.heat)object.visible=false;});this.scene.remove(this.trailMesh);this.trailMesh.geometry.dispose();this.trailMesh.material.dispose();}
}
