// @ts-check
import * as THREE from 'three';
import { markHeat } from '../../sensory/HeatSignature.js';

const RINGS=34;
const SIDES=12;

function bodyGeometry(){const positions=new Float32Array(RINGS*SIDES*3),normals=new Float32Array(RINGS*SIDES*3),uvs=new Float32Array(RINGS*SIDES*2),colors=new Float32Array(RINGS*SIDES*3),indices=[];for(let ring=0;ring<RINGS;ring++){for(let side=0;side<SIDES;side++){const vertex=ring*SIDES+side,uv=vertex*2,t=ring/(RINGS-1),angle=side/SIDES*Math.PI*2;uvs[uv]=side/SIDES;uvs[uv+1]=t;const shade=.72+.2*Math.sin(angle*2+ring*.7);colors[vertex*3]=shade;colors[vertex*3+1]=shade*.91;colors[vertex*3+2]=shade*.75;if(ring<RINGS-1){const next=vertex+SIDES,nextSide=ring*SIDES+(side+1)%SIDES,nextRingSide=next+(side+1)%SIDES-side;indices.push(vertex,next,nextSide,next,nextRingSide,nextSide);}}}const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(positions,3));geometry.setAttribute('normal',new THREE.BufferAttribute(normals,3));geometry.setAttribute('uv',new THREE.BufferAttribute(uvs,2));geometry.setAttribute('color',new THREE.BufferAttribute(colors,3));geometry.setIndex(indices);return geometry;}

function wingGeometry(side){const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute([0,0,0,side*.45,.02,0,side*.28,-.14,.05],3));geometry.setIndex([0,1,2]);geometry.computeVertexNormals();return geometry;}

export class SnakeRig {
  /** @param {THREE.Scene} scene @param {THREE.Vector3} anchor @param {number} index */
  constructor(scene,anchor,index){
    this.scene=scene;this.anchor=anchor.clone();this.index=index;this.group=new THREE.Group();this.group.name=`Cuban boa visual adapter ${index+1}`;scene.add(this.group);
    this.geometry=bodyGeometry();
    this.scaleMaterial=new THREE.MeshPhysicalMaterial({color:index===1?0x3b3328:0x332d25,roughness:.7,clearcoat:.12,vertexColors:true});
    this.body=new THREE.Mesh(this.geometry,this.scaleMaterial);this.body.castShadow=true;this.body.receiveShadow=true;this.group.add(this.body);
    this.heatBody=new THREE.Mesh(this.geometry,new THREE.MeshBasicMaterial({color:0xb43c22,transparent:true,opacity:.38,depthWrite:false,depthTest:true,blending:THREE.AdditiveBlending,fog:true}));markHeat(this.heatBody,'snakeBody',.62);this.group.add(this.heatBody);
    this.echoUniforms={strength:{value:0},motion:{value:0}};this.echoBody=new THREE.Mesh(this.geometry,new THREE.ShaderMaterial({uniforms:this.echoUniforms,transparent:true,depthWrite:false,depthTest:true,side:THREE.DoubleSide,blending:THREE.AdditiveBlending,vertexShader:`varying vec2 vUv;varying vec3 vNormalW;varying vec3 vWorld;void main(){vUv=uv;vNormalW=normalize(normalMatrix*normal);vec4 w=modelMatrix*vec4(position,1.);vWorld=w.xyz;gl_Position=projectionMatrix*viewMatrix*w;}`,fragmentShader:`uniform float strength;uniform float motion;varying vec2 vUv;varying vec3 vNormalW;varying vec3 vWorld;void main(){float organic=.55+.45*sin(vUv.y*180.+sin(vUv.x*42.)*3.+motion*8.);float fresnel=pow(1.-abs(dot(normalize(cameraPosition-vWorld),normalize(vNormalW))),1.4);float alpha=strength*(.12+organic*.2+fresnel*.34);if(alpha<.012)discard;gl_FragColor=vec4(.72,.74,.42,alpha);}`}));this.echoBody.renderOrder=5;this.group.add(this.echoBody);

    this.head=new THREE.Mesh(new THREE.IcosahedronGeometry(.52,2),this.scaleMaterial);this.head.scale.set(.82,.62,1.25);this.head.castShadow=true;this.group.add(this.head);const bellyMaterial=new THREE.MeshStandardMaterial({color:0x66513b,roughness:.8});this.snout=new THREE.Mesh(new THREE.SphereGeometry(.34,12,8),bellyMaterial);this.snout.scale.set(1,.55,1.12);this.snout.position.z=.43;this.head.add(this.snout);this.jaw=new THREE.Mesh(new THREE.SphereGeometry(.31,12,7,0,Math.PI*2,0,Math.PI*.55),bellyMaterial);this.jaw.scale.set(1,.46,1.15);this.jaw.position.set(0,-.2,.43);this.head.add(this.jaw);
    const eyeMaterial=new THREE.MeshBasicMaterial({color:0xc8a86d});for(const side of [-1,1]){const eye=new THREE.Mesh(new THREE.SphereGeometry(.047,8,6),eyeMaterial);eye.position.set(side*.31,.11,.37);this.head.add(eye);for(let p=0;p<4;p++){const pit=new THREE.Mesh(new THREE.SphereGeometry(.024,6,5),new THREE.MeshBasicMaterial({color:0x070504}));pit.position.set(side*(.22+p*.038),-.05,.55-p*.04);this.head.add(pit);}}
    this.tongue=new THREE.Mesh(new THREE.CylinderGeometry(.007,.01,.44,4),new THREE.MeshBasicMaterial({color:0x8a2c2a}));this.tongue.rotation.x=Math.PI/2;this.tongue.position.set(0,-.04,.77);this.head.add(this.tongue);
    this.heatHead=new THREE.Mesh(new THREE.IcosahedronGeometry(.54,1),new THREE.MeshBasicMaterial({color:0xff8b45,transparent:true,opacity:.72,depthWrite:false,depthTest:true,blending:THREE.AdditiveBlending,fog:true}));this.heatHead.scale.copy(this.head.scale);markHeat(this.heatHead,'snakeHead',.82);this.group.add(this.heatHead);
    this.echoHead=new THREE.Mesh(new THREE.IcosahedronGeometry(.56,1),this.echoBody.material);this.echoHead.scale.copy(this.head.scale);this.echoHead.renderOrder=5;this.group.add(this.echoHead);
    this.anchorContact=new THREE.Mesh(new THREE.TorusGeometry(.62,.16,8,18,Math.PI*1.55),this.scaleMaterial);this.anchorContact.position.copy(anchor);this.anchorContact.rotation.x=Math.PI*.5;this.group.add(this.anchorContact);
    this.captureVisual=this.createCaptureVisual();this.head.add(this.captureVisual);

    this.headPosition=anchor.clone().add(new THREE.Vector3(0,-3,0));this.aimDirection=new THREE.Vector3(0,-.08,1);this.echoAlert=0;this.echoDelay=0;this.pendingEcho=0;this.captureTime=0;this.controlPoints=Array.from({length:6},()=>new THREE.Vector3());this.curve=new THREE.CatmullRomCurve3(this.controlPoints);this.point=new THREE.Vector3();this.nextPoint=new THREE.Vector3();this.tangent=new THREE.Vector3();this.normal=new THREE.Vector3();this.binormal=new THREE.Vector3();this.reference=new THREE.Vector3();this.offset=new THREE.Vector3();this.headQuaternion=new THREE.Quaternion();this.forward=new THREE.Vector3(0,0,1);this.bodyBounds=new THREE.Sphere(anchor.clone(),4);this.visualState={state:'idle',charge:0,awareness:0,headPosition:this.headPosition,direction:this.aimDirection};
  }

  createCaptureVisual(){const group=new THREE.Group();group.position.set(0,-.08,.82);const body=new THREE.Mesh(new THREE.CapsuleGeometry(.08,.2,3,6),new THREE.MeshStandardMaterial({color:0x211915,roughness:.9}));body.rotation.x=Math.PI/2;group.add(body);for(const side of [-1,1]){const wing=new THREE.Mesh(wingGeometry(side),new THREE.MeshStandardMaterial({color:0x34241d,transparent:true,opacity:.7,side:THREE.DoubleSide}));group.add(wing);}group.visible=false;return group;}

  /** @param {number} dt @param {THREE.Vector3} headPosition @param {THREE.Vector3} direction @param {string} state @param {number} charge */
  update(dt,headPosition,direction,state,charge){
    this.headPosition.copy(headPosition);this.aimDirection.copy(direction);this.visualState.state=state;this.visualState.charge=charge;this.visualState.awareness=this.echoAlert;const time=performance.now()*.001,side=this.index%2?1:-1,tension=state==='prepare'?charge:state==='lunge'?1:state==='recover' ? .55 : 0,breathing=state==='prepare'?1-charge*.9:1;
    const p=this.controlPoints;p[0].copy(this.anchor);p[1].copy(this.anchor).add(this.offset.set(side*(1.55-tension*.3),-.38,Math.sin(time*.32+this.index)*.55));p[2].copy(this.anchor).add(this.offset.set(-side*(1.35-tension*.25),-1.08,.72+tension*.22));p[3].copy(this.anchor).lerp(headPosition,.48).add(this.offset.set(side*(.72+tension*.72),-.35,Math.sin(time*.7)*.16*breathing));p[4].copy(headPosition).addScaledVector(direction,-(1.35+tension*.55)).add(this.offset.set(-side*tension*.28,.08,0));p[5].copy(headPosition);
    this.updateBodyGeometry(tension,time,breathing);this.head.position.copy(headPosition);this.headQuaternion.setFromUnitVectors(this.forward,direction);this.head.quaternion.copy(this.headQuaternion);this.heatHead.position.copy(headPosition);this.heatHead.quaternion.copy(this.headQuaternion);this.echoHead.position.copy(headPosition);this.echoHead.quaternion.copy(this.headQuaternion);
    const jawOpen=state==='lunge' ? .58 : state==='capture' ? .46 : charge*.15;this.jaw.rotation.x=-jawOpen;this.tongue.visible=Math.sin(time*2.7+this.index*2)>.86&&state==='idle';if(this.echoDelay>0){this.echoDelay-=dt;if(this.echoDelay<=0){this.alert(this.pendingEcho);this.pendingEcho=0;}}this.echoAlert=Math.max(0,this.echoAlert-dt*(state==='lunge' ? .38 : .62));this.echoUniforms.strength.value=this.echoAlert;this.echoUniforms.motion.value=time+(state==='lunge'?1:0);this.captureTime=Math.max(0,this.captureTime-dt);this.captureVisual.visible=this.captureTime>0;if(this.captureTime>0){const struggle=Math.sin(time*42)*Math.min(1,this.captureTime*3);this.captureVisual.rotation.z=struggle*.18;this.captureVisual.children[1].rotation.z=struggle*.5;this.captureVisual.children[2].rotation.z=-struggle*.5;}this.bodyBounds.center.copy(this.anchor).lerp(headPosition,.5);this.bodyBounds.radius=this.anchor.distanceTo(headPosition)*.5+.8;
  }

  updateBodyGeometry(tension,time,breathing){const positions=this.geometry.attributes.position.array,normals=this.geometry.attributes.normal.array;for(let ring=0;ring<RINGS;ring++){const t=ring/(RINGS-1);this.curve.getPoint(t,this.point);this.curve.getTangent(t,this.tangent).normalize();this.reference.set(0,1,0);if(Math.abs(this.tangent.dot(this.reference))>.9)this.reference.set(1,0,0);this.normal.crossVectors(this.tangent,this.reference).normalize();this.binormal.crossVectors(this.tangent,this.normal).normalize();const taper=THREE.MathUtils.lerp(.48,.25,t);const muscle=1+tension*.08*Math.sin(t*Math.PI)+Math.sin(time*1.25+t*8)*.012*breathing;const radius=taper*muscle;for(let side=0;side<SIDES;side++){const angle=side/SIDES*Math.PI*2,cos=Math.cos(angle),sin=Math.sin(angle),at=(ring*SIDES+side)*3;this.offset.copy(this.normal).multiplyScalar(cos*radius).addScaledVector(this.binormal,sin*radius*.88);positions[at]=this.point.x+this.offset.x;positions[at+1]=this.point.y+this.offset.y;positions[at+2]=this.point.z+this.offset.z;normals[at]=this.offset.x/radius;normals[at+1]=this.offset.y/(radius*.88);normals[at+2]=this.offset.z/radius;}}this.geometry.attributes.position.needsUpdate=true;this.geometry.attributes.normal.needsUpdate=true;}

  alert(amount=1){this.echoAlert=Math.max(this.echoAlert,amount);}
  scheduleEcho(delay,amount=1){this.echoDelay=Math.max(0,delay);this.pendingEcho=Math.max(this.pendingEcho,amount);}
  captureBat(duration=.82){this.captureTime=duration;this.captureVisual.visible=true;}
  getMouthWorldPosition(target=new THREE.Vector3()){return this.head.localToWorld(target.set(0,-.08,.82));}
  getCaptureAttachment(){return this.captureVisual;}
  getBodyBounds(){return this.bodyBounds;}
  getHeatEmitters(){return [this.heatHead,this.heatBody];}
  getEchoResponders(){return [this.echoHead,this.echoBody];}
  getVisualState(){return this.visualState;}
  dispose(){this.scene.remove(this.group);this.group.traverse((object)=>{if(object.isMesh){object.geometry.dispose();object.material.dispose();}});}
}
