// @ts-check
import * as THREE from 'three';
import { SNAKE_ANCHORS } from '../../world/NavigationVolumes.js';
import { SnakeController } from './SnakeController.js';
import { SnakeRig } from './SnakeRig.js';
import { SnakeAI } from './SnakeAI.js';
export class SnakeNetwork {
  /** @param {THREE.Scene} scene @param {import('../../core/EventBus.js').EventBus} events @param {import('../../world/SpatialQuerySystem.js').SpatialQuerySystem} spatial */ constructor(scene,events,spatial){this.scene=scene;this.events=events;this.spatial=spatial;this.selected=0;this.playerControlled=false;this.controllers=SNAKE_ANCHORS.map((anchor)=>new SnakeController(anchor.position,events));this.rigs=SNAKE_ANCHORS.map((anchor,i)=>new SnakeRig(scene,anchor.position,i));this.ai=this.controllers.map(()=>new SnakeAI());this.dynamicFeatures=this.controllers.flatMap((controller,index)=>[{id:`snake-${index}-head`,kind:'snake',center:controller.headPosition,radius:.7,reflectivity:1,dynamic:true,owner:controller},{id:`snake-${index}-coils`,kind:'snake',center:controller.anchor.clone(),radius:1.5,reflectivity:.82,dynamic:true,owner:controller}]);this.spatial.setDynamicFeatures(this.dynamicFeatures);this.unsubscribe=events.on('echolocation-pulse',({origin,range})=>{this.controllers.forEach((controller,i)=>{const distance=controller.anchor.distanceTo(origin);if(distance<range){controller.awareness=Math.max(controller.awareness,1-distance/range);this.rigs[i].scheduleEcho(distance/21.5,controller.awareness);}});});}
  /** @param {number} dt @param {import('../../core/InputManager.js').InputManager} input @param {import('../../core/Settings.js').Settings} settings @param {import('../bat/BatAgent.js').BatAgent[]} bats */
  update(dt,input,settings,bats){if(this.playerControlled){if(input.consume('KeyQ'))this.switch(-1);if(input.consume('KeyE'))this.switch(1);}for(let i=0;i<this.controllers.length;i++){const controller=this.controllers[i];if(this.playerControlled&&i===this.selected)controller.playerUpdate(dt,input,settings);else{let target=null,best=Infinity;for(const bat of bats){if(!bat.active)continue;const distance=bat.position.distanceTo(controller.anchor);if(distance<best&&this.spatial.hasLineOfSight(controller.headPosition,bat.position,controller)){best=distance;target=bat;}}this.ai[i].update(dt,controller,target);}this.rigs[i].update(dt,controller.headPosition,controller.direction,controller.strike.state,controller.strike.charge);const headFeature=this.dynamicFeatures[i*2],bodyFeature=this.dynamicFeatures[i*2+1];headFeature.center=controller.headPosition;bodyFeature.center.copy(controller.anchor).lerp(controller.headPosition,.38);}}
  switch(delta){this.selected=(this.selected+delta+this.controllers.length)%this.controllers.length;this.events.emit('snake-switched',{index:this.selected,controller:this.controllers[this.selected]});}
  /** @returns {{from:THREE.Vector3,to:THREE.Vector3,controller:SnakeController,index:number}[]} */ activeStrikes(){return this.controllers.map((controller,index)=>({from:controller.strike.previous,to:controller.strike.position,controller,index})).filter(({controller})=>controller.strike.state==='lunge'&&!controller.strike.hit);}
  tacticalData(){return this.controllers.map((controller)=>({position:controller.headPosition,state:controller.strike.state}));}
  dispose(){this.unsubscribe();this.spatial.setDynamicFeatures([]);this.rigs.forEach((rig)=>rig.dispose());}
}
