// @ts-check
import * as THREE from 'three';
export class SnakeRig {
  /** @param {THREE.Scene} scene @param {THREE.Vector3} anchor @param {number} index */
  constructor(scene,anchor,index){this.scene=scene;this.anchor=anchor.clone();this.index=index;this.group=new THREE.Group();this.group.name=`Cuban boa ${index+1}`;scene.add(this.group);const scaleMaterial=new THREE.MeshPhysicalMaterial({color:index===1?0x302922:0x29251f,roughness:.72,clearcoat:.08});const bellyMaterial=new THREE.MeshStandardMaterial({color:0x5c4936,roughness:.82});this.segments=[];const segmentGeo=new THREE.SphereGeometry(1,10,7);for(let i=0;i<16;i++){const segment=new THREE.Mesh(segmentGeo,scaleMaterial);const taper=1-i/22;segment.scale.set(.34*taper,.3*taper,.48*taper);segment.castShadow=true;this.group.add(segment);this.segments.push(segment);}this.head=new THREE.Mesh(new THREE.SphereGeometry(.48,12,8),scaleMaterial);this.head.scale.set(.82,.62,1.25);this.head.castShadow=true;this.group.add(this.head);this.snout=new THREE.Mesh(new THREE.BoxGeometry(.48,.25,.48),bellyMaterial);this.snout.position.z=.42;this.head.add(this.snout);this.jaw=new THREE.Mesh(new THREE.BoxGeometry(.46,.12,.45),bellyMaterial);this.jaw.position.set(0,-.18,.44);this.head.add(this.jaw);const eyeMaterial=new THREE.MeshBasicMaterial({color:0xc3a26d});for(const side of [-1,1]){const eye=new THREE.Mesh(new THREE.SphereGeometry(.045,7,5),eyeMaterial);eye.position.set(side*.32,.11,.35);this.head.add(eye);for(let p=0;p<3;p++){const pit=new THREE.Mesh(new THREE.SphereGeometry(.025,5,4),new THREE.MeshBasicMaterial({color:0x080604}));pit.position.set(side*(.25+p*.035),-.05,.52-p*.045);this.head.add(pit);}}this.tongue=new THREE.Mesh(new THREE.CylinderGeometry(.008,.008,.42,4),new THREE.MeshBasicMaterial({color:0x7a2523}));this.tongue.rotation.x=Math.PI/2;this.tongue.position.set(0,-.04,.72);this.head.add(this.tongue);this.glow=new THREE.PointLight(0xe9774e,0,5,2);this.head.add(this.glow);this.headPosition=anchor.clone().add(new THREE.Vector3(0,-3,0));this.aimDirection=new THREE.Vector3(0,-.08,1);this.echoAlert=0;}
  /** @param {number} dt @param {THREE.Vector3} headPosition @param {THREE.Vector3} direction @param {string} state @param {number} charge */
  update(dt,headPosition,direction,state,charge){this.headPosition.copy(headPosition);this.aimDirection.copy(direction);const time=performance.now()*.001;const points=[this.anchor.clone(),this.anchor.clone().add(new THREE.Vector3(Math.sin(time*.35+this.index)*1.4,-.5,Math.cos(time*.3)*.8)),this.anchor.clone().add(new THREE.Vector3(this.index%2?1.6:-1.6,-1.5,.8)),headPosition.clone().addScaledVector(direction,-1.3),headPosition.clone()];const curve=new THREE.CatmullRomCurve3(points);for(let i=0;i<this.segments.length;i++){const t=i/(this.segments.length+1);const p=curve.getPoint(t),next=curve.getPoint(Math.min(1,t+.02));const segment=this.segments[i];segment.position.copy(p);segment.lookAt(next);const tension=1+charge*.1*Math.sin(t*Math.PI);segment.scale.x*=1;segment.scale.y*=1;segment.rotation.z+=Math.sin(time*1.1+i*.6)*.018;}
    this.head.position.copy(headPosition);this.head.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),direction);this.jaw.rotation.x=state==='lunge'||state==='capture'?-.42-charge*.18:-charge*.12;this.tongue.visible=Math.sin(time*2.7+this.index*2)>.82&&state==='idle';this.echoAlert=Math.max(0,this.echoAlert-dt*.7);this.glow.intensity=this.echoAlert*1.8;}
  alert(amount=1){this.echoAlert=Math.max(this.echoAlert,amount);}
  dispose(){this.scene.remove(this.group);this.group.traverse((object)=>{if(object.isMesh){object.geometry.dispose();if(Array.isArray(object.material))object.material.forEach((m)=>m.dispose());else object.material.dispose();}});}
}
