// @ts-check
import * as THREE from 'three';
import { SNAKE_ANCHORS } from '../../world/NavigationVolumes.js';
import { SnakeController } from './SnakeController.js';
import { SnakeRig } from './SnakeRig.js';
import { SnakeAI } from './SnakeAI.js';
import { Random } from '../../core/Random.js';
import { ModelAdapter } from '../../assets/ModelAdapter.js';
import { HERO_BAT_METADATA } from '../../assets/ModelMetadata.js';
export class SnakeNetwork {
  constructor(scene,events,spatial,options={}){this.scene=scene;this.events=events;this.spatial=spatial;this.random=options.random||new Random('fallback-snakes');this.difficulty=options.difficulty||{snakeReaction:1};this.director=options.director||{pressure:1,density:1,profile:{ambush:1}};this.selected=0;this.playerControlled=false;this.switchCooldown=0;this.used=new Set([0]);this.controllers=SNAKE_ANCHORS.map(anchor=>new SnakeController(anchor.position,events));this.rigs=SNAKE_ANCHORS.map((anchor,i)=>new SnakeRig(scene,anchor.position,i));if(options.assets&&options.heroBatModel!==false){const factory=()=>{const adapter=new ModelAdapter(options.assets,this.events,HERO_BAT_METADATA);return adapter.load(new THREE.Group(),true).then(ready=>ready?adapter:null);};this.rigs.forEach(rig=>rig.setCapturedFactory(factory));}this.ai=this.controllers.map((_,i)=>new SnakeAI(this.random.fork(`snake-${i}`),this.difficulty,this.director,i));this.dynamicFeatures=this.controllers.flatMap((controller,index)=>[{id:`snake-${index}-head`,kind:'snake',center:controller.headPosition,radius:.7,reflectivity:1,dynamic:true,owner:controller},{id:`snake-${index}-coils`,kind:'snake',center:controller.anchor.clone(),radius:1.5,reflectivity:.82,dynamic:true,owner:controller}]);this.spatial.setDynamicFeatures(this.dynamicFeatures);this.unsubscribe=[events.on('echolocation-pulse',({origin,range,kind})=>{this.controllers.forEach((controller,i)=>{const distance=controller.anchor.distanceTo(origin);if(distance<range){controller.awareness=Math.max(controller.awareness,(1-distance/range)*(kind==='full'?1:.45));this.ai[i].memory.hear();this.rigs[i].scheduleEcho(distance/21.5,controller.awareness);}});}),events.on('bat-captured',({bat,route})=>{if(!bat)return;let nearest=0,distance=Infinity;this.controllers.forEach((c,i)=>{const d=c.headPosition.distanceTo(bat.position);if(d<distance){distance=d;nearest=i;}});if(distance<3)this.ai[nearest].success(route||bat.routeId);})];}
  update(dt,input,settings,bats){this.switchCooldown=Math.max(0,this.switchCooldown-dt);if(this.playerControlled){if(input.consumeAction('switchLeft'))this.switch(-1);if(input.consumeAction('switchRight'))this.switch(1);}for(let i=0;i<this.controllers.length;i++){const controller=this.controllers[i];if(this.playerControlled&&i===this.selected)controller.playerUpdate(dt,input,settings);else{let target=null,best=Infinity;for(const bat of bats){if(!bat.active)continue;const distance=bat.position.distanceTo(controller.anchor);if(distance<best&&this.spatial.hasLineOfSight(controller.headPosition,bat.position,controller)){best=distance;target=bat;}}this.ai[i].update(dt,controller,target,bats,this.controllers);}
      if(controller.strike.justResolved){controller.strike.justResolved=false;if(!controller.strike.hit){const reason=this.classifyMiss(controller);this.rigs[i].missReason=reason;this.events.emit('strike-missed',{index:i,reason,position:controller.strike.end.clone(),player:this.playerControlled&&i===this.selected});}}
      this.rigs[i].update(dt,controller.headPosition,controller.direction,controller.strike.state,controller.strike.charge);this.dynamicFeatures[i*2].center=controller.headPosition;this.dynamicFeatures[i*2+1].center.copy(controller.anchor).lerp(controller.headPosition,.38);}}
  /** Distinguish overreach, obstruction, and poor lead without touching strike gameplay. */
  classifyMiss(controller){const end=controller.strike.end;if(this.spatial.resolveSphere(end.clone(),.2))return 'obstruction';if(controller.strike.releaseCharge<.5)return 'overreach';return 'lead';}
  switch(delta){if(this.switchCooldown>0)return false;this.selected=(this.selected+delta+this.controllers.length)%this.controllers.length;this.switchCooldown=.42;this.used.add(this.selected);const controller=this.controllers[this.selected];controller.focus=0;controller.switchLock=.38;controller.strike.cancel();this.events.emit('snake-switched',{index:this.selected,controller});return true;}
  activeStrikes(){const active=[];for(let index=0;index<this.controllers.length;index++){const controller=this.controllers[index];if(controller.strike.state==='lunge'&&!controller.strike.hit)active.push({from:controller.strike.previous,to:controller.strike.position,controller,index});}return active;}
  tacticalData(){return this.controllers.map((controller,index)=>({position:controller.headPosition,state:controller.strike.state,alertness:this.ai[index].memory.confidence}));}
  sightPlayer(position){for(let i=0;i<this.controllers.length;i++){const controller=this.controllers[i];if(controller.headPosition.distanceToSquared(position)<225&&this.spatial.hasLineOfSight(controller.headPosition,position,controller))this.ai[i].memory.playerSightings=Math.min(120,this.ai[i].memory.playerSightings+1);}}
  alertness(){return this.ai.reduce((sum,ai)=>sum+ai.memory.confidence,0)/this.ai.length;}
  dispose(){this.unsubscribe.forEach(fn=>fn());this.spatial.setDynamicFeatures([]);this.rigs.forEach(rig=>rig.dispose());}
}
