// @ts-check
import * as THREE from 'three';
import { SnakeStrike } from './SnakeStrike.js';
export class SnakeController {
  constructor(anchor,events){this.anchor=anchor.clone();this.events=events;this.yaw=0;this.pitch=-.08;this.offset=0;this.extension=0;this.focus=0;this.switchLock=0;this.strikeQuality=0;this.strike=new SnakeStrike();this.headPosition=anchor.clone().add(new THREE.Vector3(0,-3,0));this.direction=new THREE.Vector3(0,-.08,1).normalize();this.awareness=0;this.local=new THREE.Vector3();this.anchorOffset=new THREE.Vector3();}
  playerUpdate(dt,input,settings){this.switchLock=Math.max(0,this.switchLock-dt);const mouse=input.consumeMouse(),focused=input.actionDown('focus'),s=settings.get('mouseSensitivity')*.0011*(focused ? .38 : 1);this.focus+=(Number(focused)-this.focus)*Math.min(1,dt*4);this.yaw=THREE.MathUtils.clamp(this.yaw-mouse.x*s,-1.05,1.05);this.pitch=THREE.MathUtils.clamp(this.pitch-mouse.y*s,-.62,.48);this.offset=THREE.MathUtils.clamp(this.offset+input.axis('moveX')*dt*1.4,-1.8,1.8);this.extension=THREE.MathUtils.clamp(this.extension+input.axis('moveY')*dt*1.2,-.5,1.4);this.updateDirection();if(input.actionDown('strike')&&this.switchLock<=0)this.strike.prepare(dt*(1+this.focus*.18));if(input.actionReleased('strike')){this.strikeQuality=Math.max(0,1-Math.abs(this.pitch+.05)*.65-Math.abs(this.offset)*.12-Math.abs(this.extension-.45)*.16);if(this.strike.release(this.headPosition,this.direction))this.events.emit('snake-strike-started',{controller:this,quality:this.strikeQuality});else this.strike.cancel();}this.advance(dt);}
  advance(dt){const state=this.strike.update(dt);if(state==='lunge'||state==='recover'||state==='capture')this.headPosition.copy(this.strike.position);else this.headPosition.copy(this.anchor).add(this.anchorOffset.set(this.offset,-3-this.extension,0)).addScaledVector(this.direction,.35);this.awareness=Math.max(0,this.awareness-dt*.16);}
  updateDirection(){this.direction.set(Math.sin(this.yaw)*Math.cos(this.pitch),Math.sin(this.pitch),Math.cos(this.yaw)*Math.cos(this.pitch)).normalize();}
  aiUpdate(target,dt){const local=this.local.subVectors(target,this.headPosition).normalize(),targetYaw=Math.atan2(local.x,local.z),targetPitch=Math.asin(THREE.MathUtils.clamp(local.y,-1,1));this.yaw+=THREE.MathUtils.clamp(targetYaw-this.yaw,-dt*.75,dt*.75);this.pitch+=THREE.MathUtils.clamp(targetPitch-this.pitch,-dt*.6,dt*.6);this.updateDirection();this.advance(dt);}
}
