// @ts-check
import * as THREE from 'three';
import { CAVE_LANDMARKS, SNAKE_ANCHORS, caveSectionAt } from './NavigationVolumes.js';
import { markHeat } from '../sensory/HeatSignature.js';

const seeded=index=>{const value=Math.sin(index*91.733+3.17)*43758.5453;return value-Math.floor(value);};
const _v=new THREE.Vector3(),_n=new THREE.Vector3();

function displace(geometry,amount,frequency,seed=0){const pos=geometry.attributes.position,nor=geometry.attributes.normal;for(let i=0;i<pos.count;i++){_v.fromBufferAttribute(pos,i);_n.fromBufferAttribute(nor,i);const broad=Math.sin(_v.x*frequency+seed*1.7)*Math.cos(_v.y*frequency*.83+seed*2.3)*Math.sin(_v.z*frequency*1.13+seed*3.1),fine=Math.sin(_v.x*frequency*2.7+seed)*Math.sin(_v.z*frequency*2.3+seed*1.3)*.5;_v.addScaledVector(_n,(broad+fine)*amount);pos.setXYZ(i,_v.x,_v.y,_v.z);}geometry.computeVertexNormals();return geometry;}
function echoCharacter(mesh,materials,fill,surfaceOffset=.015){mesh.onBeforeRender=()=>{const profile=mesh.userData.echoProfile||{};materials.echoUniforms.geometryFill.value=fill;materials.echoUniforms.surfaceOffset.value=surfaceOffset;materials.echoUniforms.landmarkStrength.value=profile.strength??1;materials.echoUniforms.landmarkDetail.value=profile.detail??1;materials.echoUniforms.landmarkMemory.value=profile.memory??1;materials.echoUniforms.wetResponse.value=profile.wet??0;};return mesh;}

/** Variable elliptical shell with authored chambers, constrictions, bedding, and ceiling pockets. */
function caveShell(path){const segments=144,sides=32,positions=[],colors=[],uvs=[],indices=[];for(let ring=0;ring<=segments;ring++){const t=ring/segments,center=path.getPoint(t),section=caveSectionAt(center),z=center.z,roost=Math.exp(-Math.pow((z+44)/10,2)),mouth=Math.max(0,(z-38)/16);for(let side=0;side<sides;side++){const angle=side/sides*Math.PI*2,ceiling=Math.max(0,Math.sin(angle)),floor=Math.max(0,-Math.sin(angle));const bedding=Math.sin(angle*5+z*.075)*.32+Math.sin(angle*11-z*.043)*.12;const pocket=roost*ceiling*(.55+.45*Math.sin(angle*9+z*.31));const fracture=mouth*Math.sin(angle*3+z*.2)*.45;const rx=section.xRadius+bedding+fracture,ry=section.yRadius+bedding*.65+pocket;positions.push(section.centerX+Math.cos(angle)*rx,section.centerY+Math.sin(angle)*ry,z);const seep=Math.max(0,Math.sin(z*.18+angle*2.3))**8*(ceiling*.35+floor*.8),nearMouth=Math.max(0,(z-30)/24),tone=THREE.MathUtils.clamp(.46+ceiling*.07-floor*.09-seep*.11+nearMouth*.025,.24,.62);colors.push(tone*.72,tone*(.93+nearMouth*.04),tone*.84);uvs.push(side/sides*8,t*22);}}for(let ring=0;ring<segments;ring++)for(let side=0;side<sides;side++){const a=ring*sides+side,b=ring*sides+(side+1)%sides,c=(ring+1)*sides+side,d=(ring+1)*sides+(side+1)%sides;indices.push(a,c,b,b,c,d);}const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));geometry.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));geometry.setAttribute('uv',new THREE.Float32BufferAttribute(uvs,2));geometry.setIndex(indices);geometry.computeVertexNormals();return geometry;}

function draperyGeometry(width=13,height=10,folds=6){const cols=30,rows=12,positions=[],uvs=[],indices=[];for(let y=0;y<=rows;y++)for(let x=0;x<=cols;x++){const u=x/cols,v=y/rows,z=(u-.5)*width,drop=v*height,fold=Math.sin(u*Math.PI*2*folds)*.48*(.35+v*.65)+Math.sin(u*Math.PI*2*2.2)*.18;positions.push(fold,-drop,z);uvs.push(u,v);}for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){const a=y*(cols+1)+x,b=a+1,c=a+cols+1,d=c+1;indices.push(a,c,b,b,c,d);}const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));geometry.setAttribute('uv',new THREE.Float32BufferAttribute(uvs,2));geometry.setIndex(indices);geometry.computeVertexNormals();return geometry;}

function batSilhouetteGeometry(){const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute([0,0,0,-.17,-.04,.02,-.08,.08,0,0,0,0,.17,-.04,.02,.08,.08,0,0,.02,0,-.04,-.16,0,.04,-.16,0],3));geometry.setIndex([0,1,2,3,4,5,6,7,8]);geometry.computeVertexNormals();return geometry;}
function leafGeometry(){const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute([0,-.5,0,-.22,-.12,.02,-.16,.22,0,0,.5,0,.16,.22,0,.22,-.12,.02],3));geometry.setIndex([0,1,2,0,2,3,0,3,4,0,4,5]);geometry.computeVertexNormals();return geometry;}
function readableShell(geometry){const colors=geometry.attributes.color;for(let i=0;i<colors.count;i++)colors.setXYZ(i,.68+colors.getX(i)*.25,.7+colors.getY(i)*.26,.69+colors.getZ(i)*.25);colors.needsUpdate=true;return geometry;}

export class CaveGenerator{
  /** @param {THREE.Scene} scene @param {import('./CaveMaterials.js').CaveMaterials} materials */
  constructor(scene,materials){this.scene=scene;this.materials=materials;this.group=new THREE.Group();this.group.name='Authored Cueva de los Vientos';scene.add(this.group);this.obstacles=[];this.spatialFeatures=[];this.echoLandmarks=[];this.thermalFadeMaterials=[];this.roostMatrices=[];this.leafBases=[];this.elapsed=0;this.lastRoostCount=-1;this.airflow=0;}

  build(){const path=new THREE.CatmullRomCurve3([new THREE.Vector3(-3,2,-54),new THREE.Vector3(1,3,-35),new THREE.Vector3(-4,5,-15),new THREE.Vector3(3,4,8),new THREE.Vector3(-2,6,27),new THREE.Vector3(0,7,52)]);const tunnel=readableShell(caveShell(path)),shell=new THREE.Mesh(tunnel,this.materials.rock),echoShell=echoCharacter(new THREE.Mesh(tunnel,this.materials.echo),this.materials,.5,-.055);shell.receiveShadow=true;shell.name='Authored limestone chamber shell';echoShell.renderOrder=3;echoShell.name='Echolocation chamber shell';this.group.add(shell,echoShell);
    this.addRegionalGeology();this.addRoostVault();this.addGuanoShelf();this.addFangCeiling();this.addSplitColumn();this.addBellChamber();this.addBrokenPillar();this.addMoonGallery();this.addEntranceAndExterior();this.addWetness();this.addRoostEcology();this.roostColony.material.color.set(0x2c211a);this.addAmbushSupports();this.addMenuBoa();this.addMenuBats();this.refineCollisionProxies();this.echoMeshes=[];this.group.traverse(object=>{if(object.material===this.materials.echo){object.visible=false;this.echoMeshes.push(object);}});this.configureEchoLandmarks();return{path,obstacles:this.obstacles,spatialFeatures:this.spatialFeatures,echoLandmarks:this.echoLandmarks};}

  configureEchoLandmarks(){const profiles=[['Roost Vault',{strength:.82,detail:.42,memory:1.35}],['Guano Shelf',{strength:.68,detail:.28,memory:1.25}],['Fang Ceiling',{strength:.72,detail:.1,memory:.58}],['Split Column',{strength:1.28,detail:.38,memory:1.18}],['Sentinel Column',{strength:1.08,detail:.32,memory:1.05}],['Curtain Wall',{strength:1.18,detail:.55,memory:1.24,wet:1}],['Broken Pillar',{strength:.9,detail:.24,memory:.76}],['Moon Gallery',{strength:.84,detail:.3,memory:.82,wet:.45}],['Moon Gate',{strength:.94,detail:.34,memory:.9,wet:.55}],['Breakdown',{strength:.58,detail:.12,memory:.62}],['chamber shell',{strength:.78,detail:.34,memory:1}]];for(const mesh of this.echoMeshes){const match=profiles.find(([label])=>mesh.name.includes(label));mesh.userData.echoProfile=match?match[1]:{strength:.86,detail:.42,memory:.9};}}
  addPair(geometry,material,position,scale,rotation,name,fill=.32){const normal=new THREE.Mesh(geometry,material),echo=echoCharacter(new THREE.Mesh(geometry,this.materials.echo),this.materials,fill);normal.position.copy(position);echo.position.copy(position);normal.scale.copy(scale);echo.scale.copy(scale);normal.rotation.copy(rotation);echo.rotation.copy(rotation);normal.castShadow=true;normal.receiveShadow=true;echo.renderOrder=3;normal.name=name;echo.name=`${name} echo`;this.group.add(normal,echo);return normal;}
  register(id,kind,center,radius,reflectivity=.85,label=id){this.obstacles.push({center:center.clone(),radius,label});this.spatialFeatures.push({id,kind,center:center.clone(),radius,reflectivity});this.echoLandmarks.push(center.clone());}

  addRegionalGeology(){const geometry=displace(new THREE.IcosahedronGeometry(1,2),.22,2.1,1.3),clusters=[[-9,-4,-43,10],[-10,-3,-6,9],[9,-4,8,10],[-8,-5,20,9],[8,-3,36,8]],transforms=[];let seed=40;for(const [cx,cy,cz,count] of clusters)for(let i=0;i<count;i++){const side=Math.sign(cx),position=new THREE.Vector3(cx+(seeded(seed++)-.5)*4.5,cy+seeded(seed++)*6,cz+(seeded(seed++)-.5)*13),scale=new THREE.Vector3(1.1+seeded(seed++)*2.4,.7+seeded(seed++)*2.2,1.2+seeded(seed++)*3.1),rotation=new THREE.Euler(seeded(seed++)*2.4,seeded(seed++)*3,(seeded(seed++)-.5)*1.4);if(Math.abs(position.x)<5.5)position.x=side*5.5;transforms.push({position,scale,rotation});}const rocks=new THREE.InstancedMesh(geometry,this.materials.rubble,transforms.length),echo=echoCharacter(new THREE.InstancedMesh(geometry,this.materials.echo,transforms.length),this.materials,.2),matrix=new THREE.Matrix4(),quaternion=new THREE.Quaternion();transforms.forEach((item,index)=>{quaternion.setFromEuler(item.rotation);matrix.compose(item.position,quaternion,item.scale);rocks.setMatrixAt(index,matrix);echo.setMatrixAt(index,matrix);});rocks.instanceMatrix.needsUpdate=true;echo.instanceMatrix.needsUpdate=true;rocks.castShadow=true;rocks.receiveShadow=true;rocks.name='Clustered breakdown and fractured limestone';echo.name='Breakdown echo silhouettes';echo.renderOrder=3;this.group.add(rocks,echo);}

  addRoostVault(){const ribGeometry=displace(new THREE.CylinderGeometry(1,1,1,10,3),.12,2.7,4.2),ribs=new THREE.InstancedMesh(ribGeometry,this.materials.dry,8),echo=echoCharacter(new THREE.InstancedMesh(ribGeometry,this.materials.echo,8),this.materials,.27),matrix=new THREE.Matrix4(),q=new THREE.Quaternion(),scale=new THREE.Vector3();for(let i=0;i<8;i++){const z=-51+i*2.05;q.setFromEuler(new THREE.Euler(0,0,Math.PI/2+(seeded(i+100)-.5)*.16));scale.set(4.6+seeded(i+110)*2.3,.5+seeded(i+120)*.45,.65+seeded(i+130)*.6);matrix.compose(new THREE.Vector3(-1+Math.sin(i*.7)*1.8,13.2+seeded(i+140)*1.2,z),q,scale);ribs.setMatrixAt(i,matrix);echo.setMatrixAt(i,matrix);}ribs.instanceMatrix.needsUpdate=true;echo.instanceMatrix.needsUpdate=true;ribs.castShadow=true;ribs.name='Roost Vault bedding ribs';echo.name='Roost Vault rib echoes';echo.renderOrder=3;this.group.add(ribs,echo);this.spatialFeatures.push({id:'roost-vault',kind:'cavity',center:CAVE_LANDMARKS.roostVault.clone(),radius:6.5,reflectivity:.7});this.echoLandmarks.push(CAVE_LANDMARKS.roostVault.clone());}

  addGuanoShelf(){const geometry=displace(new THREE.IcosahedronGeometry(1,3),.16,1.7,7.7);this.addPair(geometry,this.materials.dry,CAVE_LANDMARKS.guanoShelf,new THREE.Vector3(7.2,1.2,7.8),new THREE.Euler(.08,.12,-.08),'Guano Shelf',.46);for(let i=0;i<3;i++)this.register(`guano-shelf-${i}`,'shelf',new THREE.Vector3(2.4+i*2.7,8,-34+i*1.4),2.1,.84,'Guano Shelf mass');}

  addFangCeiling(){const geometry=displace(new THREE.ConeGeometry(1,1,11,5),.1,3.2,9.1);geometry.translate(0,-.5,0);const count=19,fangs=new THREE.InstancedMesh(geometry,this.materials.wet,count),echo=echoCharacter(new THREE.InstancedMesh(geometry,this.materials.echo,count),this.materials,.08),matrix=new THREE.Matrix4(),q=new THREE.Quaternion(),scale=new THREE.Vector3();for(let i=0;i<count;i++){const lane=i%3,x=-8.4+lane*3.1+(seeded(i+220)-.5)*1.4,z=-31+Math.floor(i/3)*1.8+seeded(i+230)*1.2,length=3.2+seeded(i+240)*5.8;q.setFromEuler(new THREE.Euler((seeded(i+250)-.5)*.08,seeded(i+260)*Math.PI,(seeded(i+270)-.5)*.15));scale.set(.22+seeded(i+280)*.48,length,.22+seeded(i+290)*.48);matrix.compose(new THREE.Vector3(x,15.3-seeded(i+300)*.8,z),q,scale);fangs.setMatrixAt(i,matrix);echo.setMatrixAt(i,matrix);if(i%3===0)this.register(`fang-${i}`,'stalactite',new THREE.Vector3(x,15-length*.5,z),.55+Math.max(scale.x,scale.z),.92,'Fang Ceiling stalactite');}fangs.instanceMatrix.needsUpdate=true;echo.instanceMatrix.needsUpdate=true;fangs.castShadow=true;fangs.name='Fang Ceiling clustered stalactites';echo.name='Fang Ceiling layered returns';echo.renderOrder=3;this.group.add(fangs,echo);}

  addSplitColumn(){const geometry=displace(new THREE.CylinderGeometry(1.7,2.25,19,16,7),.28,.65,18.4),positions=[new THREE.Vector3(-7.5,3.1,-15.7),new THREE.Vector3(-3.2,3.4,-14.4)];positions.forEach((position,i)=>{this.addPair(geometry,i?this.materials.damp:this.materials.formation,position,new THREE.Vector3(i?.86:1,1,i?.94:1.08),new THREE.Euler(0,(i-.5)*.2,(i?1:-1)*.07),`Split Column ${i?'east':'west'} lobe`,.5);for(let y=-3;y<=9;y+=4)this.register(`split-column-${i}-${y}`,'column',new THREE.Vector3(position.x,y,position.z),1.75,.96,'Split Column lobe');});this.spatialFeatures.push({id:'split-cleft',kind:'cavity',center:new THREE.Vector3(-5.35,4,-15),radius:1.35,reflectivity:1});this.echoLandmarks.push(new THREE.Vector3(-5.35,4,-15));}

  addBellChamber(){const sentinel=displace(new THREE.CylinderGeometry(2,2.7,18,15,6),.25,.72,31.2);this.addPair(sentinel,this.materials.formation,new THREE.Vector3(7,2,7),new THREE.Vector3(1,1,1),new THREE.Euler(0,.2,-.05),'Sentinel Column',.43);for(let y=-3;y<=8;y+=3.7)this.register(`sentinel-${y}`,'column',new THREE.Vector3(7,y,7),2.15,.9,'Sentinel Column');const curtain=draperyGeometry(14,10,7);this.addPair(curtain,this.materials.wet,new THREE.Vector3(10.1,13,-1),new THREE.Vector3(1,1,1),new THREE.Euler(0,0,0),'Curtain Wall',.58);for(let z=-4;z<=10;z+=3.5)this.spatialFeatures.push({id:`curtain-fold-${z}`,kind:'drapery',center:new THREE.Vector3(9.5,7,z),radius:1.15,reflectivity:.88});this.echoLandmarks.push(CAVE_LANDMARKS.curtainWall.clone());}

  addBrokenPillar(){const geometry=displace(new THREE.CylinderGeometry(1.45,1.8,8,12,5),.22,.9,42.5),pieces=[{p:new THREE.Vector3(-1,-4.4,16),r:new THREE.Euler(.2,0,1.22)},{p:new THREE.Vector3(3.4,-4.8,20.5),r:new THREE.Euler(-.1,.5,1.42)}];pieces.forEach((piece,i)=>{this.addPair(geometry,this.materials.fracture,piece.p,new THREE.Vector3(1,1,1),piece.r,`Broken Pillar section ${i+1}`,.36);for(let j=-2;j<=2;j++)this.register(`broken-pillar-${i}-${j}`,'rubble',piece.p.clone().add(new THREE.Vector3(j*1.25,i?.15*j:.35*j,j*.25)),1.35,.76,'Broken Pillar');});const rubble=displace(new THREE.IcosahedronGeometry(1,1),.18,2.4,50),mesh=new THREE.InstancedMesh(rubble,this.materials.rubble,18),matrix=new THREE.Matrix4(),q=new THREE.Quaternion(),scale=new THREE.Vector3();for(let i=0;i<18;i++){const p=new THREE.Vector3(-5+seeded(i+400)*11,-7.1+seeded(i+410)*1.5,11+seeded(i+420)*15);q.setFromEuler(new THREE.Euler(seeded(i+430)*2,seeded(i+440)*2,seeded(i+450)*2));scale.set(.35+seeded(i+460)*1.1,.25+seeded(i+470)*.8,.4+seeded(i+480)*1.4);matrix.compose(p,q,scale);mesh.setMatrixAt(i,matrix);}mesh.instanceMatrix.needsUpdate=true;mesh.castShadow=true;mesh.name='Broken Pillar breakdown apron';this.group.add(mesh);}

  addMoonGallery(){const geometry=displace(new THREE.IcosahedronGeometry(1,2),.25,1.8,61.7),shelves=[{p:new THREE.Vector3(-8,10,25),s:new THREE.Vector3(4.2,.9,4.7)},{p:new THREE.Vector3(7,4,31),s:new THREE.Vector3(3.8,.75,5.2)},{p:new THREE.Vector3(-7,-1,38),s:new THREE.Vector3(4.6,1.1,3.8)}];shelves.forEach((item,i)=>{this.addPair(geometry,i===2?this.materials.algae:this.materials.damp,item.p,item.s,new THREE.Euler(.12,i*.35,(i-1)*.12),`Moon Gallery fractured shelf ${i+1}`,.32);this.register(`moon-shelf-${i}`,'shelf',item.p.clone(),2.7,.78,'Moon Gallery shelf');});}

  addEntranceAndExterior(){this.exterior=new THREE.Group();this.exterior.name='Bounded Cuban exterior glimpse';this.group.add(this.exterior);const skyMaterial=new THREE.ShaderMaterial({uniforms:{thermal:{value:0}},side:THREE.DoubleSide,depthWrite:false,vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'uniform float thermal;varying vec2 vUv;void main(){vec3 low=vec3(.018,.04,.036),high=vec3(.075,.13,.15);vec3 c=mix(low,high,smoothstep(0.,1.,vUv.y));c+=vec3(.02,.035,.035)*sin(vUv.x*17.)*.08;gl_FragColor=vec4(mix(c,vec3(.006),thermal),1.);}'});this.thermalFadeMaterials.push(skyMaterial);const sky=new THREE.Mesh(new THREE.PlaneGeometry(70,42),skyMaterial);sky.position.set(0,13,82);sky.rotation.y=Math.PI;sky.name='Exterior night sky';this.exterior.add(sky);
    const moonMaterial=new THREE.MeshBasicMaterial({color:0xb8cfca,transparent:true,opacity:.72,depthWrite:false}),moon=new THREE.Mesh(new THREE.CircleGeometry(1.55,32),moonMaterial);moon.position.set(-13,19,80.8);moon.rotation.y=Math.PI;moon.name='Distant moon';this.exterior.add(moon);this.moonMaterial=moonMaterial;
    const terrainGeometry=new THREE.BufferGeometry();terrainGeometry.setAttribute('position',new THREE.Float32BufferAttribute([-35,-9,0,-35,2,0,-22,5,0,-12,1,0,-2,4,0,9,0,0,20,6,0,35,2,0,35,-9,0],3));terrainGeometry.setIndex([0,1,2,0,2,3,0,3,4,0,4,5,0,5,6,0,6,7,0,7,8]);terrainGeometry.computeVertexNormals();const terrain=new THREE.Mesh(terrainGeometry,this.materials.terrain);terrain.position.set(0,0,76);terrain.name='Distant mogote silhouettes';this.exterior.add(terrain);
    const trunkGeometry=new THREE.CylinderGeometry(.2,.34,7,6),canopyGeometry=displace(new THREE.IcosahedronGeometry(1,1),.18,2.3,72),trunks=new THREE.InstancedMesh(trunkGeometry,this.materials.exteriorVegetation,12),canopies=new THREE.InstancedMesh(canopyGeometry,this.materials.exteriorVegetation,20),matrix=new THREE.Matrix4(),q=new THREE.Quaternion(),scale=new THREE.Vector3();for(let i=0;i<12;i++){const x=-25+seeded(i+510)*50,z=61+seeded(i+520)*12,y=-1+seeded(i+530)*4;q.setFromEuler(new THREE.Euler(0,seeded(i+540)*3,0));scale.set(1,.8+seeded(i+550)*1.1,1);matrix.compose(new THREE.Vector3(x,y,z),q,scale);trunks.setMatrixAt(i,matrix);for(let c=0;c<(i%3?1:2);c++){scale.set(2+seeded(i+c+560)*2,1.1+seeded(i+c+570)*1.8,1.6+seeded(i+c+580)*2.5);matrix.compose(new THREE.Vector3(x+(c-.5)*1.8,y+4.1+c,z),q,scale);canopies.setMatrixAt(i+c*12>19?i:i+c*12,matrix);}}trunks.instanceMatrix.needsUpdate=true;canopies.instanceMatrix.needsUpdate=true;trunks.name='Distant tropical trunks';canopies.name='Distant tropical canopy';this.exterior.add(trunks,canopies);
    const archGeometry=displace(new THREE.IcosahedronGeometry(1,2),.2,1.9,81),arch=[];for(const side of [-1,1])for(let i=0;i<5;i++)arch.push({p:new THREE.Vector3(side*(6.8+i*.45),1.5+i*2.4,48.5+i*.45),s:new THREE.Vector3(2.8-i*.18,2.7,3.1)});for(let i=0;i<5;i++)arch.push({p:new THREE.Vector3(-5+i*2.5,13.4+Math.sin(i/4*Math.PI)*1.2,50),s:new THREE.Vector3(2.4,1.9,2.8)});arch.forEach((item,i)=>{this.addPair(archGeometry,i%4===0?this.materials.algae:this.materials.damp,item.p,item.s,new THREE.Euler(seeded(i+600),seeded(i+610),seeded(i+620)),`Moon Gate arch stone ${i+1}`,.3);if(i%2===0)this.register(`moon-gate-${i}`,'arch',item.p.clone(),1.7,.82,'Moon Gate arch');});
    const leaf=leafGeometry(),leafCount=34,leaves=new THREE.InstancedMesh(leaf,this.materials.exteriorVegetation,leafCount);for(let i=0;i<leafCount;i++){const side=i%2?-1:1,p=new THREE.Vector3(side*(5.2+seeded(i+650)*4),1+seeded(i+660)*12,49+seeded(i+670)*8),s=.7+seeded(i+680)*1.9;this.leafBases.push({position:p,scale:new THREE.Vector3(s,s*(1.2+seeded(i+690)*.9),s),phase:seeded(i+700)*6.28});q.setFromEuler(new THREE.Euler((seeded(i+710)-.5)*.8,seeded(i+720)*3,(seeded(i+730)-.5)*1.2));matrix.compose(p,q,this.leafBases[i].scale);leaves.setMatrixAt(i,matrix);}leaves.instanceMatrix.needsUpdate=true;leaves.name='Moon Gate hanging leaves';this.exterior.add(leaves);this.entranceLeaves=leaves;
    const insectData=new Float32Array(30*3);for(let i=0;i<30;i++){insectData[i*3]=(seeded(i+740)-.5)*18;insectData[i*3+1]=2+seeded(i+750)*10;insectData[i*3+2]=53+seeded(i+760)*12;}const insectGeometry=new THREE.BufferGeometry();insectGeometry.setAttribute('position',new THREE.BufferAttribute(insectData,3));this.insects=new THREE.Points(insectGeometry,new THREE.PointsMaterial({color:0x9eaa83,size:.035,transparent:true,opacity:.35,depthWrite:false}));this.insects.name='Sparse entrance insects';this.exterior.add(this.insects);
    const hazeMaterial=new THREE.MeshBasicMaterial({color:0x78918b,transparent:true,opacity:.035,depthWrite:false,side:THREE.DoubleSide});for(let i=0;i<3;i++){const haze=new THREE.Mesh(new THREE.PlaneGeometry(18+i*7,10+i*3),hazeMaterial);haze.position.set((i-1)*2,6+i,55+i*7);haze.rotation.y=Math.PI;haze.name=`Entrance humidity layer ${i+1}`;this.exterior.add(haze);}this.spatialFeatures.push({id:'mouth',kind:'mouth',center:CAVE_LANDMARKS.moonGate.clone(),radius:5.8,reflectivity:.82});this.echoLandmarks.push(CAVE_LANDMARKS.moonGate.clone());}

  addWetness(){const streakGeometry=new THREE.PlaneGeometry(1,1),streaks=[],zones=[{x:9.82,z:2,count:13},{x:-9.9,z:-25,count:9},{x:-8.8,z:33,count:8}];let seed=800;for(const zone of zones)for(let i=0;i<zone.count;i++){streaks.push({p:new THREE.Vector3(zone.x+(seeded(seed++)-.5)*.5,2+seeded(seed++)*10,zone.z+(seeded(seed++)-.5)*13),s:new THREE.Vector3(.035+seeded(seed++)*.1,1.2+seeded(seed++)*4.7,1),side:Math.sign(zone.x)});}const mesh=new THREE.InstancedMesh(streakGeometry,this.materials.water,streaks.length),matrix=new THREE.Matrix4(),q=new THREE.Quaternion();streaks.forEach((item,i)=>{q.setFromEuler(new THREE.Euler(0,item.side>0?-Math.PI/2:Math.PI/2,(seeded(i+860)-.5)*.12));matrix.compose(item.p,q,item.s);mesh.setMatrixAt(i,matrix);});mesh.instanceMatrix.needsUpdate=true;mesh.name='Localized wet seep streaks';this.group.add(mesh);for(const [x,z,s] of [[7,7,2.4],[-2,18,2.1],[-6,34,1.8]]){const pool=new THREE.Mesh(new THREE.CircleGeometry(s,24),this.materials.water);pool.position.set(x,-7.85,z);pool.rotation.x=-Math.PI/2;pool.scale.y=.45;pool.name='Damp floor collection';this.group.add(pool);}}

  addRoostEcology(){const beds=[];for(let i=0;i<20;i++)beds.push({x:(seeded(i+900)-.5)*14,z:-50+seeded(i+910)*21,s:2+seeded(i+920)*3.8,r:seeded(i+930)*Math.PI});const patches=new THREE.InstancedMesh(new THREE.PlaneGeometry(1,1),this.materials.guano,beds.length),matrix=new THREE.Matrix4(),q=new THREE.Quaternion(),scale=new THREE.Vector3();beds.forEach((item,i)=>{q.setFromEuler(new THREE.Euler(-Math.PI/2,0,item.r));scale.setScalar(item.s);matrix.compose(new THREE.Vector3(item.x,-7.86,item.z),q,scale);patches.setMatrixAt(i,matrix);});patches.instanceMatrix.needsUpdate=true;patches.name='Primary roost guano field';this.group.add(patches);
    const geometry=batSilhouetteGeometry(),count=96,material=new THREE.MeshStandardMaterial({color:0x100d0b,roughness:1,side:THREE.DoubleSide}),colony=new THREE.InstancedMesh(geometry,material,count),heatMaterial=new THREE.MeshBasicMaterial({color:0xb64b2d,transparent:true,opacity:.24,depthWrite:false,blending:THREE.AdditiveBlending,side:THREE.DoubleSide}),heat=new THREE.InstancedMesh(geometry,heatMaterial,count);markHeat(heat,'membrane',.48);for(let i=0;i<count;i++){const p=new THREE.Vector3(-7+seeded(i+940)*14,12.1+seeded(i+950)*2.2,-51+seeded(i+960)*17),s=.55+seeded(i+970)*.65;this.roostMatrices.push({position:p,scale:s,phase:seeded(i+980)*6.28});}colony.name='Roost Vault hanging colony';heat.name='Roost colony thermal field';this.roostColony=colony;this.roostHeat=heat;this.group.add(colony,heat);this.spatialFeatures.push({id:'roost-colony',kind:'roost',center:new THREE.Vector3(-1,13,-43),radius:6,reflectivity:.5});}

  addAmbushSupports(){const geometry=displace(new THREE.IcosahedronGeometry(1,2),.25,1.9,99);const supports=[{name:'Fang Perch cradle',p:SNAKE_ANCHORS[0].position.clone().add(new THREE.Vector3(-.4,1.1,-.5)),s:new THREE.Vector3(2.7,.9,2.5),m:this.materials.wet},{name:'Curtain Ledge rib',p:SNAKE_ANCHORS[1].position.clone().add(new THREE.Vector3(.7,.9,.1)),s:new THREE.Vector3(3.2,.75,2.2),m:this.materials.damp},{name:'Moon Perch overhang',p:SNAKE_ANCHORS[2].position.clone().add(new THREE.Vector3(-.6,1,.5)),s:new THREE.Vector3(3.4,.85,2.8),m:this.materials.algae}];supports.forEach((support,i)=>{this.addPair(geometry,support.m,support.p,support.s,new THREE.Euler(.12,i*.7,(i-1)*.12),support.name,.38);this.register(`boa-support-${i}`,'shelf',support.p.clone(),2.25,.86,support.name);});}

  addMenuBoa(){const group=new THREE.Group(),material=new THREE.MeshStandardMaterial({color:0x3d2d22,roughness:.88});for(let i=0;i<3;i++){const coil=new THREE.Mesh(new THREE.TorusGeometry(.75-i*.11,.13-i*.018,7,20),material);coil.rotation.x=Math.PI/2+i*.12;coil.position.y=i*.12;group.add(coil);}const head=new THREE.Mesh(new THREE.SphereGeometry(.27,10,7),material);head.scale.set(.72,.5,1.1);head.position.set(.2,-.25,.8);group.add(head);group.position.set(7.8,8.2,4);group.rotation.y=-1.1;group.name='Menu concealed boa silhouette';this.menuBoa=group;this.group.add(group);}

  addMenuBats(){const count=7,bats=new THREE.InstancedMesh(batSilhouetteGeometry(),new THREE.MeshBasicMaterial({color:0x050807,side:THREE.DoubleSide}),count),matrix=new THREE.Matrix4(),q=new THREE.Quaternion(),scale=new THREE.Vector3();for(let i=0;i<count;i++){q.setFromEuler(new THREE.Euler((seeded(i+1100)-.5)*.35,seeded(i+1110)*Math.PI,(seeded(i+1120)-.5)*.5));scale.setScalar(1.4+seeded(i+1130)*1.5);matrix.compose(new THREE.Vector3(-6+seeded(i+1140)*12,7+seeded(i+1150)*5,18+i*4.1),q,scale);bats.setMatrixAt(i,matrix);}bats.instanceMatrix.needsUpdate=true;bats.name='Menu distant bat silhouettes';this.menuBats=bats;this.group.add(bats);}

  update(dt,director=null,airflow=0){this.elapsed+=dt;this.airflow+=(airflow-this.airflow)*Math.min(1,dt*2);if(this.roostColony){const progress=director?THREE.MathUtils.clamp(director.elapsed/director.duration,0,1):.16,remaining=Math.max(18,Math.round(this.roostMatrices.length*(1-progress*.78))),matrix=new THREE.Matrix4(),q=new THREE.Quaternion(),scale=new THREE.Vector3();if(remaining!==this.lastRoostCount||Math.floor(this.elapsed*8)!==Math.floor((this.elapsed-dt)*8)){this.roostMatrices.forEach((item,i)=>{const active=i<remaining,stir=director?.density||.1,flutter=active&&i>remaining-12?Math.sin(this.elapsed*(5+stir*4)+item.phase)*.08:0;q.setFromEuler(new THREE.Euler(0,item.phase,Math.PI+flutter));scale.setScalar(active?item.scale:0);matrix.compose(item.position,q,scale);this.roostColony.setMatrixAt(i,matrix);this.roostHeat.setMatrixAt(i,matrix);});this.roostColony.instanceMatrix.needsUpdate=true;this.roostHeat.instanceMatrix.needsUpdate=true;this.lastRoostCount=remaining;}}
    if(this.entranceLeaves){const matrix=new THREE.Matrix4(),q=new THREE.Quaternion();this.leafBases.forEach((item,i)=>{const sway=Math.sin(this.elapsed*(.55+this.airflow*.7)+item.phase)*(.08+this.airflow*.15);q.setFromEuler(new THREE.Euler(sway*.3,item.phase,sway));matrix.compose(item.position,q,item.scale);this.entranceLeaves.setMatrixAt(i,matrix);});this.entranceLeaves.instanceMatrix.needsUpdate=true;}if(this.insects){this.insects.rotation.z=Math.sin(this.elapsed*.17)*.03;this.insects.position.x=Math.sin(this.elapsed*.29)*.4;}}
  setMenuMode(active){if(this.menuBoa)this.menuBoa.visible=active;if(this.menuBats)this.menuBats.visible=active;}
  refineCollisionProxies(){for(const name of ['Split Column east lobe','Split Column east lobe echo']){const mesh=this.group.getObjectByName(name);if(mesh)mesh.position.x=-4.1;}for(const name of ['Sentinel Column','Sentinel Column echo']){const mesh=this.group.getObjectByName(name);if(mesh)mesh.position.x=9;}for(const feature of this.spatialFeatures){if(feature.id.startsWith('split-column-1-'))feature.center.x=-4.1;if(feature.id.startsWith('sentinel-'))feature.center.x=9;if(feature.id.startsWith('guano-shelf-')){feature.radius=1.45;feature.center.y=7;}if(feature.id==='moon-shelf-1')feature.radius=1.35;}for(const obstacle of this.obstacles){if(obstacle.label==='Split Column lobe'&&obstacle.center.x>-5)obstacle.center.x=-4.1;if(obstacle.label==='Sentinel Column')obstacle.center.x=9;if(obstacle.label==='Guano Shelf mass'){obstacle.radius=1.45;obstacle.center.y=7;}if(obstacle.label==='Moon Gallery shelf'&&obstacle.center.x>0)obstacle.radius=1.35;}this.obstacles=this.obstacles.filter(obstacle=>obstacle.label!=='Fang Ceiling stalactite');this.spatialFeatures=this.spatialFeatures.filter(feature=>!feature.id.startsWith('fang-'));for(const [id,x,y,z] of [['fang-proxy-west',-5.3,10.5,-29],['fang-proxy-east',-2.2,9.4,-25],['fang-proxy-mid',-5.3,10.8,-21]])this.register(id,'stalactite',new THREE.Vector3(x,y,z),.72,.92,'Fang Ceiling proxy');}
  setEchoVisible(active){for(const mesh of this.echoMeshes)mesh.visible=active;}
  setQuality(profile){if(this.exterior)this.exterior.visible=true;if(this.insects)this.insects.geometry.setDrawRange(0,profile.particles<100?10:profile.particles<250?20:30);}
  setThermalBlend(blend){for(const material of this.thermalFadeMaterials)if(material.uniforms.thermal)material.uniforms.thermal.value=blend;if(this.moonMaterial)this.moonMaterial.opacity=THREE.MathUtils.lerp(.72,.08,blend);}
}
