// @ts-check
import * as THREE from 'three';
import { BatPlayer } from '../entities/bat/BatPlayer.js';
import { BatFlock } from '../entities/bat/BatFlock.js';
import { SnakeNetwork } from '../entities/snake/SnakeNetwork.js';
import { EcholocationSystem } from '../sensory/EcholocationSystem.js';
import { ThreatAwareness } from '../sensory/ThreatAwareness.js';
import { BatObjective } from './Objectives.js';
import { Scoring } from './Scoring.js';
import { AirflowSystem } from '../world/AirflowSystem.js';
import { ModelAdapter } from '../assets/ModelAdapter.js';
import { HERO_BAT_METADATA } from '../assets/ModelMetadata.js';
import { BAT_START,ENTRANCE } from '../world/NavigationVolumes.js';
export class BatMode {
  constructor(context){Object.assign(this,context);this.player=new BatPlayer(this.camera,this.input,this.settings,this.world,this.events);this.player.reset(BAT_START);this.flock=new BatFlock(this.scene,Math.round(this.settings.profile().bats*this.difficulty.density),this.events,{random:this.random.fork('flock'),routes:this.routes,director:this.director});this.snakes=new SnakeNetwork(this.scene,this.events,this.world.spatial,{random:this.random.fork('snakes'),difficulty:this.difficulty,director:this.director});this.snakes.playerControlled=false;this.echo=new EcholocationSystem(this.scene,this.world,this.events,this.settings);this.threat=new ThreatAwareness();this.airflow=new AirflowSystem(this.events);this.objective=new BatObjective();this.scoring=new Scoring(this.difficulty);this.model=new ModelAdapter(this.assets,this.events,HERO_BAT_METADATA);this.model.load(this.camera,this.settings.get('heroBatModel')).then(ready=>{if(ready)this.player.rig.root.visible=false;});this.callHold=0;this.callArmed=false;this.ended=false;this.toExit=new THREE.Vector3();this.forward=new THREE.Vector3();this.routeSample=new THREE.Vector3();this.hud.show();this.onboarding.cue('bat-flap','Flap to build speed. Glide to recover rhythm.');this.unsubscribe=[this.events.on('echolocation-pulse',({kind})=>{if(kind==='quick')this.scoring.quickCalls++;else this.scoring.fullCalls++;this.onboarding.succeed(kind==='quick'?'bat-quick':'bat-full');}),this.events.on('player-collision',()=>{this.scoring.collisions++;this.director.disturb(.6);}),this.events.on('snake-strike-started',({controller})=>{const distance=controller.headPosition.distanceTo(this.player.position);this.scoring.closestStrike=Math.min(this.scoring.closestStrike,distance);if(distance<12){this.threat.trigger(1);this.onboarding.cue('bat-heard','A boa heard that call. Change line or speed.');}})];}
  fixedUpdate(dt){if(this.ended)return;this.director.update(dt);this.player.fixedUpdate(dt);this.snakes.sightPlayer(this.player.position);this.snakes.update(dt,this.input,this.settings,this.flock.agents);this.flock.update(dt,this.player.position,this.snakes.tacticalData());for(const strike of this.snakes.activeStrikes()){const distance=this.world.spatial.pointSegmentDistance(this.player.position,strike.from,strike.to);this.scoring.closestStrike=Math.min(this.scoring.closestStrike,distance);if(distance<.8){strike.controller.strike.capture();this.snakes.rigs[strike.index].captureBat();this.events.emit('bat-captured',{position:this.player.position.clone(),player:true});this.finish(false,'Taken in darkness','The boa adapted to the line you kept returning to.');return;}if(distance<2.1){strike.controller.strike.hit=true;this.scoring.nearMisses++;this.threat.trigger(.8);this.events.emit('near-miss',{position:this.player.position.clone()});}else this.flock.captureAlong(strike.from,strike.to,.62);}if(this.objective.escaped(this.player.position))this.finish(true,'Into moonlight','Moving air catches beneath your wings. The departure continues behind you.');}
  update(dt){if(this.ended)return;const callDown=this.input.actionDown('echolocate');if(callDown&&!this.callArmed){this.callArmed=true;this.callHold=0;this.onboarding.cue('bat-quick','Tap the call input for a quiet nearby picture.');}if(this.callArmed&&callDown)this.callHold+=dt;if(this.callArmed&&this.input.actionReleased('echolocate')){const kind=this.callHold<.32?'quick':'full';if(this.echo.emit(this.player.position,kind)){this.onboarding.succeed(kind==='quick'?'bat-quick':'bat-full');if(kind==='quick')this.onboarding.cue('bat-full','Hold and release for a deeper, louder reconstruction.');}this.callArmed=false;}this.echo.update(dt);this.threat.update(dt);this.player.update(dt);this.airflow.update(dt,this.player.position,this.director);if(this.input.actionDown('flap'))this.onboarding.succeed('bat-flap');const distance=this.objective.distance(this.player.position);this.toExit.subVectors(ENTRANCE,this.player.position);this.forward.set(Math.sin(this.player.controller.yaw),0,Math.cos(this.player.controller.yaw));const bearing=Math.atan2(this.toExit.x,this.toExit.z)-Math.atan2(this.forward.x,this.forward.z);let nearest='central',best=Infinity;for(const route of this.routes.routes){this.routes.sample(route.id,this.player.position.z,this.routeSample);const d=this.routeSample.distanceToSquared(this.player.position);if(d<best){best=d;nearest=route.id;}}this.scoring.route=nearest;this.scoring.flockContext=this.flock.agents.reduce((n,b)=>n+(b.active&&b.position.distanceToSquared(this.player.position)<16?1:0),0);this.scoring.score=this.scoring.batScore(100-distance,this.player.velocity.length());this.model.update(dt,{flap:this.input.actionDown('flap'),brake:this.input.actionDown('brake'),bank:this.player.controller.bank});this.hud.update({distance,score:this.scoring.score,energy:this.player.controller.energy,echo:this.echo.readiness(),threat:this.threat.level,bearing,call:this.callHold>.32?'DEEP CALL':'QUICK CALL',device:this.input.activeDevice});}
  finish(success,title,description){if(this.ended)return;this.ended=true;this.onEnd({success,outcome:success?'ESCAPE RECORDED':'PREDATION RECORDED',title,description,stats:[{value:`${this.scoring.elapsed().toFixed(1)}s`,label:'Escape time'},{value:`${this.scoring.quickCalls} / ${this.scoring.fullCalls}`,label:'Quick / deep calls'},{value:this.scoring.collisions,label:'Collisions'},{value:`${this.scoring.closestStrike<90?this.scoring.closestStrike.toFixed(1):'—'} m`,label:'Closest strike'},{value:this.scoring.route,label:'Route used'},{value:this.scoring.score.toLocaleString(),label:'Field score'}]});}
  speed(){return this.player.velocity.length();}activeBats(){return this.flock.activeCount();}sensoryTime(){return this.echo.lastUpdateMs;}dispose(){this.hud.hide();this.unsubscribe.forEach(fn=>fn());this.model.dispose();this.player.dispose();this.echo.dispose();this.flock.dispose();this.snakes.dispose();}
}
