// @ts-check
import * as THREE from 'three';
import { BatFlock } from '../entities/bat/BatFlock.js';
import { SnakeNetwork } from '../entities/snake/SnakeNetwork.js';
import { ThermalVisionSystem } from '../sensory/ThermalVisionSystem.js';
import { SnakeObjective } from './Objectives.js';
import { Scoring } from './Scoring.js';
import { SNAKE_ANCHORS } from '../world/NavigationVolumes.js';
export class SnakeMode {
  constructor(context){Object.assign(this,context);this.flock=new BatFlock(this.scene,this.settings.profile().bats+8,this.events);this.snakes=new SnakeNetwork(this.scene,this.events);this.snakes.playerControlled=true;this.thermal=new ThermalVisionSystem(this.scene,this.fog,this.events);this.objective=new SnakeObjective(4,68);this.scoring=new Scoring();this.ended=false;this.hud.show();this.switchTransition=0;this.wakeTimer=0;this.unsubscribe=this.events.on('snake-switched',()=>{this.switchTransition=1;document.body.classList.add('cinematic');setTimeout(()=>document.body.classList.remove('cinematic'),260);});}
  fixedUpdate(dt){if(this.ended)return;this.objective.update(dt);this.snakes.update(dt,this.input,this.settings,this.flock.agents);this.flock.update(dt,null,this.snakes.tacticalData());for(const strike of this.snakes.activeStrikes()){const captured=this.flock.captureAlong(strike.from,strike.to,.72);if(captured){strike.controller.strike.capture();if(strike.index===this.snakes.selected){this.scoring.captures++;this.events.emit('player-capture',{index:strike.index});if(this.objective.complete(this.scoring.captures)){this.finish(true,'The roost pays tribute','Four precise strikes. The colony keeps moving, but this hunting line belongs to the boas.');return;}}}}if(this.objective.expired())this.finish(false,'The stream thins','Dawn approaches. The remaining bats have passed beyond the hunting line.');}
  update(dt){if(this.ended)return;if(this.input.consume('KeyT'))this.thermal.toggle();this.wakeTimer-=dt;if(this.thermal.active&&this.wakeTimer<=0){this.wakeTimer=this.settings.get('quality')==='high' ? .07 : .13;const candidates=this.flock.agents.filter((bat)=>bat.active&&bat.velocity.length()>8.5).slice(0,this.settings.get('quality')==='high' ? 3 : 1);candidates.forEach((bat)=>this.thermal.addWake(bat.position));}this.thermal.update(dt);const controller=this.snakes.controllers[this.snakes.selected];const motion=this.settings.get('reducedCameraMotion')?0:1;this.camera.position.copy(controller.headPosition).addScaledVector(controller.direction,-.38).add(new THREE.Vector3(0,.11,0));const target=controller.headPosition.clone().addScaledVector(controller.direction,8);this.camera.lookAt(target);this.camera.rotation.z=Math.sin(performance.now()*.0007)*.012*motion;this.hud.update({post:SNAKE_ANCHORS[this.snakes.selected].label,captures:this.scoring.captures,target:this.objective.target,thermal:this.thermal.active,time:this.objective.remaining,readiness:controller.strike.readiness(),charging:controller.strike.state==='prepare'});this.switchTransition=Math.max(0,this.switchTransition-dt*4);}
  finish(success,title,description){if(this.ended)return;this.ended=true;this.onEnd({success,outcome:success?'HUNT COMPLETE':'OBSERVATION ENDED',title,description,stats:[{value:this.scoring.captures,label:'Captures'},{value:`${this.scoring.elapsed().toFixed(1)}s`,label:'Hunt time'},{value:this.scoring.snakeScore().toLocaleString(),label:'Score'}]});}
  speed(){return 0;}activeBats(){return this.flock.activeCount();}
  dispose(){this.hud.hide();this.unsubscribe();this.thermal.dispose();this.flock.dispose();this.snakes.dispose();}
}
