// @ts-check
import * as THREE from 'three';
import { BatFlock } from '../entities/bat/BatFlock.js';
import { SnakeNetwork } from '../entities/snake/SnakeNetwork.js';
import { SnakeFirstPersonRig } from '../entities/snake/SnakeFirstPersonRig.js';
import { ThermalVisionSystem } from '../sensory/ThermalVisionSystem.js';
import { SnakeObjective } from './Objectives.js';
import { Scoring } from './Scoring.js';
import { SNAKE_ANCHORS } from '../world/NavigationVolumes.js';
export class SnakeMode {
  constructor(context){Object.assign(this,context);this.flock=new BatFlock(this.scene,this.settings.profile().bats+8,this.events);this.snakes=new SnakeNetwork(this.scene,this.events,this.world.spatial);this.firstPersonRig=new SnakeFirstPersonRig(this.camera);this.snakes.playerControlled=true;this.thermal=new ThermalVisionSystem(this.scene,this.fog,this.events,this.settings,this.world);this.objective=new SnakeObjective(4,68);this.scoring=new Scoring();this.ended=false;this.hud.show();this.switchTransition=0;this.wakeTimer=0;this.switchFromPosition=new THREE.Vector3();this.switchFromQuaternion=new THREE.Quaternion();this.desiredPosition=new THREE.Vector3();this.desiredQuaternion=new THREE.Quaternion();this.targetPoint=new THREE.Vector3();this.unsubscribe=this.events.on('snake-switched',()=>{this.switchTransition=1;this.switchFromPosition.copy(this.camera.position);this.switchFromQuaternion.copy(this.camera.quaternion);this.thermal.afterimage=Math.max(this.thermal.afterimage,.7);document.body.classList.add('awareness-transfer');setTimeout(()=>document.body.classList.remove('awareness-transfer'),420);});}
  fixedUpdate(dt){if(this.ended)return;this.objective.update(dt);this.snakes.update(dt,this.input,this.settings,this.flock.agents);this.flock.update(dt,null,this.snakes.tacticalData());for(const strike of this.snakes.activeStrikes()){const captured=this.flock.captureAlong(strike.from,strike.to,.72);if(captured){strike.controller.strike.capture();this.snakes.rigs[strike.index].captureBat();if(strike.index===this.snakes.selected){this.scoring.captures++;this.events.emit('player-capture',{index:strike.index});if(this.objective.complete(this.scoring.captures)){this.finish(true,'The roost pays tribute','Four precise strikes. The colony keeps moving, but this hunting line belongs to the boas.');return;}}}}if(this.objective.expired())this.finish(false,'The stream thins','Dawn approaches. The remaining bats have passed beyond the hunting line.');}
  update(dt){if(this.ended)return;if(this.input.consume('KeyT'))this.thermal.toggle();const controller=this.snakes.controllers[this.snakes.selected];this.thermal.update(dt,this.flock.heatSources(),this.camera,controller);const reducedMotion=this.settings.get('reducedCameraMotion');const motion=reducedMotion?0:1;/* Keep the eye just beyond the world head; a separate facial adapter supplies subtle body context. */this.desiredPosition.copy(controller.headPosition).addScaledVector(controller.direction,.86);this.desiredPosition.y+=.16;this.targetPoint.copy(controller.headPosition).addScaledVector(controller.direction,8);this.camera.position.copy(this.desiredPosition);this.camera.lookAt(this.targetPoint);this.desiredQuaternion.copy(this.camera.quaternion);if(this.switchTransition>0&&!reducedMotion){const t=1-this.switchTransition,eased=t*t*(3-2*t);this.camera.position.lerpVectors(this.switchFromPosition,this.desiredPosition,eased);this.camera.quaternion.slerpQuaternions(this.switchFromQuaternion,this.desiredQuaternion,eased);}this.camera.rotateZ(Math.sin(performance.now()*.0007)*.012*motion);this.firstPersonRig.update(dt,controller,reducedMotion);this.hud.update({post:SNAKE_ANCHORS[this.snakes.selected].label,captures:this.scoring.captures,target:this.objective.target,thermal:this.thermal.active,time:this.objective.remaining,readiness:controller.strike.readiness(),charging:controller.strike.state==='prepare'});this.switchTransition=Math.max(0,this.switchTransition-dt*2.8);}
  finish(success,title,description){if(this.ended)return;this.ended=true;this.onEnd({success,outcome:success?'HUNT COMPLETE':'OBSERVATION ENDED',title,description,stats:[{value:this.scoring.captures,label:'Captures'},{value:`${this.scoring.elapsed().toFixed(1)}s`,label:'Hunt time'},{value:this.scoring.snakeScore().toLocaleString(),label:'Score'}]});}
  speed(){return 0;}activeBats(){return this.flock.activeCount();}
  sensoryTime(){return this.thermal.lastUpdateMs;}
  dispose(){this.hud.hide();this.unsubscribe();this.thermal.dispose();this.firstPersonRig.dispose();this.flock.dispose();this.snakes.dispose();}
}
