// @ts-check
import * as THREE from 'three';
import { BatFlock } from '../entities/bat/BatFlock.js';
import { SnakeNetwork } from '../entities/snake/SnakeNetwork.js';
import { SnakeFirstPersonRig } from '../entities/snake/SnakeFirstPersonRig.js';
import { ThermalVisionSystem } from '../sensory/ThermalVisionSystem.js';
import { SnakeObjective } from './Objectives.js';
import { Scoring } from './Scoring.js';
import { SNAKE_ANCHORS } from '../world/NavigationVolumes.js';
export class SnakeMode {
  constructor(context){Object.assign(this,context);this.flock=new BatFlock(this.scene,Math.round((this.settings.profile().bats+8)*this.difficulty.density),this.events,{random:this.random.fork('flock'),routes:this.routes,director:this.director});this.snakes=new SnakeNetwork(this.scene,this.events,this.world.spatial,{random:this.random.fork('snakes'),difficulty:this.difficulty,director:this.director,assets:this.assets});this.firstPersonRig=new SnakeFirstPersonRig(this.camera);this.snakes.playerControlled=true;this.thermal=new ThermalVisionSystem(this.scene,this.fog,this.events,this.settings,this.world);this.objective=new SnakeObjective(this.difficulty.target,this.difficulty.duration);this.scoring=new Scoring(this.difficulty);this.ended=false;this.switchTransition=0;this.captureImpulse=0;this.missImpulse=0;this.switchFromPosition=new THREE.Vector3();this.switchFromQuaternion=new THREE.Quaternion();this.desiredPosition=new THREE.Vector3();this.desiredQuaternion=new THREE.Quaternion();this.targetPoint=new THREE.Vector3();this.hud.show();this.onboarding.cue('snake-aim','You are anchored above the flight line. Aim the head with the mouse.');this.unsubscribe=[this.events.on('snake-switched',({index})=>{this.switchTransition=1;this.scoring.snakesUsed.add(index);this.onboarding.succeed('snake-switch');this.switchFromPosition.copy(this.camera.position);this.switchFromQuaternion.copy(this.camera.quaternion);this.thermal.afterimage=Math.max(this.thermal.afterimage,.7);document.body.classList.add('awareness-transfer');setTimeout(()=>document.body.classList.remove('awareness-transfer'),420);}),this.events.on('snake-strike-started',({controller,quality=0})=>{if(controller===this.snakes.controllers[this.snakes.selected]){this.scoring.strikes++;this.scoring.bestIntercept=Math.max(this.scoring.bestIntercept,quality);this.onboarding.succeed('snake-strike');}}),this.events.on('player-capture',()=>{this.captureImpulse=1;this.onboarding.cue('snake-switch','The lunge must recover. Switch posts to watch another flight lane.');}),this.events.on('strike-missed',({player,reason})=>{if(player){this.missImpulse=reason==='obstruction'?1:.55;this.onboarding.cue('snake-switch','The lunge had travel time and missed. Recover, or switch posts with Q / E.');}})];}
  fixedUpdate(dt){if(this.ended)return;this.director.update(dt);this.objective.update(dt);this.snakes.update(dt,this.input,this.settings,this.flock.agents);this.flock.update(dt,null,this.snakes.tacticalData());let playerLunging=false;for(const strike of this.snakes.activeStrikes()){const captured=this.flock.captureAlong(strike.from,strike.to,.72);if(strike.index===this.snakes.selected)playerLunging=true;if(captured){strike.controller.strike.capture();this.snakes.rigs[strike.index].captureBat();if(strike.index===this.snakes.selected){this.scoring.captures++;this.events.emit('player-capture',{index:strike.index});if(this.objective.complete(this.scoring.captures)){this.finish(true,'The roost pays tribute','Patience and route prediction held the flight line.');return;}}}}if(!playerLunging&&this.scoring.strikes>this.scoring.captures+this.scoring.misses)this.scoring.misses=this.scoring.strikes-this.scoring.captures;this.scoring.patience+=dt*(this.snakes.controllers[this.snakes.selected].strike.state==='idle'?1:0);if(this.objective.expired())this.finish(false,'The stream thins','Dawn approaches. The remaining bats have passed beyond the hunting line.');}
  update(dt){if(this.ended)return;const controller=this.snakes.controllers[this.snakes.selected];if(Math.abs(controller.yaw)>.025||Math.abs(controller.pitch+.08)>.025)this.onboarding.succeed('snake-aim');if(this.input.consumeAction('thermal')){this.thermal.toggle();this.onboarding.succeed('snake-thermal');}if(controller.focus>.25)this.onboarding.succeed('snake-focus');if(Math.abs(controller.offset)>.08||Math.abs(controller.extension)>.08)this.onboarding.succeed('snake-position');const learned=this.onboarding.learned;if(!learned['snake-aim'])this.onboarding.cue('snake-aim','You are anchored above the flight line. Aim the head with the mouse.');else if(!learned['snake-thermal'])this.onboarding.cue('snake-thermal','Toggle thermal perception with T to reveal warm moving bats.');else if(!learned['snake-focus'])this.onboarding.cue('snake-focus','Hold F or Right Click to narrow thermal attention around one flight path.');else if(!learned['snake-position'])this.onboarding.cue('snake-position','Use A / D and W / S to reposition within this ceiling anchor.');else if(!learned['snake-strike'])this.onboarding.cue('snake-strike','Lead a crossing bat. Hold Click to build tension; release before it reaches the strike path.');if(controller.strike.state==='prepare')this.audio?.tension(controller.headPosition,controller.strike.charge);this.thermal.update(dt,this.flock.heatSources(),this.camera,controller);const reducedMotion=this.settings.get('reducedCameraMotion'),motion=reducedMotion?0:1;this.desiredPosition.copy(controller.headPosition).addScaledVector(controller.direction,.86);this.desiredPosition.y+=.16;this.targetPoint.copy(controller.headPosition).addScaledVector(controller.direction,8);this.camera.position.copy(this.desiredPosition);this.camera.lookAt(this.targetPoint);this.desiredQuaternion.copy(this.camera.quaternion);if(this.switchTransition>0&&!reducedMotion){const t=1-this.switchTransition,eased=t*t*(3-2*t);this.camera.position.lerpVectors(this.switchFromPosition,this.desiredPosition,eased);this.camera.quaternion.slerpQuaternions(this.switchFromQuaternion,this.desiredQuaternion,eased);}this.camera.rotateZ(Math.sin(performance.now()*.0007)*.012*motion);
    // Event-tied camera impulses: capture settles through the jaw, a hard miss knocks the head.
    this.captureImpulse=Math.max(0,this.captureImpulse-dt*1.6);this.missImpulse=Math.max(0,this.missImpulse-dt*2);if(!reducedMotion){if(this.captureImpulse>0)this.camera.rotateX(-Math.sin(this.captureImpulse*Math.PI)*.06);if(this.missImpulse>0)this.camera.rotateZ(Math.sin(this.missImpulse*22)*.02*this.missImpulse);}
    this.firstPersonRig.update(dt,controller,reducedMotion);this.scoring.score=this.scoring.snakeScore();this.hud.update({post:SNAKE_ANCHORS[this.snakes.selected].label,captures:this.scoring.captures,target:this.objective.target,thermal:this.thermal.active,focus:controller.focus,time:this.objective.remaining,readiness:controller.strike.readiness()*(1-Math.min(1,controller.switchLock/.38)),charging:controller.strike.state==='prepare',device:this.input.activeDevice});this.switchTransition=Math.max(0,this.switchTransition-dt*2.8);}
  finish(success,title,description){if(this.ended)return;this.ended=true;this.onEnd({success,outcome:success?'HUNT COMPLETE':'OBSERVATION ENDED',title,description,stats:[{value:this.scoring.captures,label:'Captures'},{value:this.scoring.strikes,label:'Strikes'},{value:`${Math.round(this.scoring.accuracy()*100)}%`,label:'Accuracy'},{value:this.scoring.snakesUsed.size,label:'Boas used'},{value:this.scoring.misses,label:'Miss recovery'},{value:this.scoring.snakeScore().toLocaleString(),label:'Field score'}]});}
  speed(){return 0;}activeBats(){return this.flock.activeCount();}sensoryTime(){return this.thermal.lastUpdateMs;}dispose(){this.hud.hide();this.unsubscribe.forEach(fn=>fn());this.thermal.dispose();this.firstPersonRig.dispose();this.flock.dispose();this.snakes.dispose();}
}
