// @ts-check
import * as THREE from 'three';
import { BatAgent } from './BatAgent.js';
import { markHeat } from '../../sensory/HeatSignature.js';

export class BatFlock {
  /** @param {THREE.Scene} scene @param {number} count @param {import('../../core/EventBus.js').EventBus} events */
  constructor(scene,count,events){this.scene=scene;this.count=count;this.events=events;/** @type {BatAgent[]} */this.agents=Array.from({length:count},(_,i)=>new BatAgent(i));this.elapsed=0;this.buildMeshes();this.unsubscribe=events.on('echolocation-pulse',({origin,range})=>this.startle(origin,range));}
  buildMeshes(){const bodyGeo=new THREE.CapsuleGeometry(.14,.38,3,6);bodyGeo.rotateX(Math.PI/2);const wingGeo=new THREE.BufferGeometry();wingGeo.setAttribute('position',new THREE.Float32BufferAttribute([0,0,0,-.72,.08,-.05,-.35,-.05,.32,0,0,0,.72,.08,-.05,.35,-.05,.32],3));wingGeo.setIndex([0,1,2,3,4,5]);wingGeo.computeVertexNormals();const bodyMat=new THREE.MeshStandardMaterial({color:0x171411,roughness:.92});const wingMat=new THREE.MeshStandardMaterial({color:0x251d18,roughness:.88,transparent:true,opacity:.72,side:THREE.DoubleSide});this.bodies=new THREE.InstancedMesh(bodyGeo,bodyMat,this.count);this.wings=new THREE.InstancedMesh(wingGeo,wingMat,this.count);this.bodies.castShadow=true;this.wings.castShadow=true;this.scene.add(this.bodies,this.wings);
    const heatBodyMat=new THREE.MeshBasicMaterial({color:0xffb15b,transparent:true,opacity:.9,blending:THREE.AdditiveBlending});const heatWingMat=new THREE.MeshBasicMaterial({color:0xb64b2c,transparent:true,opacity:.46,side:THREE.DoubleSide,blending:THREE.AdditiveBlending});this.heatBodies=new THREE.InstancedMesh(bodyGeo,heatBodyMat,this.count);this.heatWings=new THREE.InstancedMesh(wingGeo,heatWingMat,this.count);markHeat(this.heatBodies,'core');markHeat(this.heatWings,'membrane');this.scene.add(this.heatBodies,this.heatWings);}
  startle(origin,range){for(const agent of this.agents){const distance=agent.position.distanceTo(origin);if(distance<range)agent.panic=Math.max(agent.panic,1-distance/range*.4);}}
  /** @param {number} dt @param {THREE.Vector3|null} playerPosition @param {{position:THREE.Vector3,state:string}[]} snakes */
  update(dt,playerPosition,snakes=[]){this.elapsed+=dt;const matrix=new THREE.Matrix4(),quat=new THREE.Quaternion(),scale=new THREE.Vector3();const up=new THREE.Vector3(0,1,0);for(const bat of this.agents){if(!bat.active){matrix.makeScale(0,0,0);this.setMatrices(bat.index,matrix);continue;}bat.panic=Math.max(0,bat.panic-dt*.35);const desired=new THREE.Vector3(Math.sin(bat.position.z*.08+bat.phase)*.55,Math.sin(this.elapsed*.7+bat.phase)*.35,8.2+bat.panic*4.5);for(const other of this.agents){if(other===bat||!other.active)continue;const d=bat.position.distanceToSquared(other.position);if(d<1.4&&d>.001)desired.addScaledVector(bat.position.clone().sub(other.position).normalize(),(1.4-d)*.8);}for(const snake of snakes){const distance=bat.position.distanceTo(snake.position);if(distance<8&&snake.state!=='recover')desired.addScaledVector(bat.position.clone().sub(snake.position).normalize(),(8-distance)*1.3);}if(playerPosition){const distance=bat.position.distanceTo(playerPosition);if(distance<2.2)desired.addScaledVector(bat.position.clone().sub(playerPosition).normalize(),2.2-distance);}const corridorX=Math.sin((bat.position.z+15)*.045)*2.2;desired.x+=(corridorX-bat.position.x)*.18;desired.y+=(3.8+Math.sin(bat.position.z*.1+bat.phase)*2-bat.position.y)*.14;bat.velocity.lerp(desired,Math.min(1,dt*(1.1+bat.panic*2)));bat.position.addScaledVector(bat.velocity,dt);if(bat.position.z>55){bat.position.z=-54-Math.random()*50;bat.position.x=(Math.random()-.5)*10;bat.active=true;bat.captured=false;}const flap=Math.sin(this.elapsed*(11+bat.panic*8)+bat.phase);quat.setFromUnitVectors(new THREE.Vector3(0,0,1),bat.velocity.clone().normalize());scale.set(1,1,1);matrix.compose(bat.position,quat,scale);this.bodies.setMatrixAt(bat.index,matrix);const wingScale=new THREE.Vector3(1,Math.max(.16,.72+.5*flap),1);matrix.compose(bat.position,quat,wingScale);this.wings.setMatrixAt(bat.index,matrix);this.heatBodies.setMatrixAt(bat.index,matrix);this.heatWings.setMatrixAt(bat.index,matrix);}this.bodies.instanceMatrix.needsUpdate=true;this.wings.instanceMatrix.needsUpdate=true;this.heatBodies.instanceMatrix.needsUpdate=true;this.heatWings.instanceMatrix.needsUpdate=true;}
  setMatrices(index,matrix){this.bodies.setMatrixAt(index,matrix);this.wings.setMatrixAt(index,matrix);this.heatBodies.setMatrixAt(index,matrix);this.heatWings.setMatrixAt(index,matrix);}
  /** @param {THREE.Vector3} from @param {THREE.Vector3} to @param {number} radius */
  captureAlong(from,to,radius){const segment=to.clone().sub(from);const lengthSq=segment.lengthSq();let best=null,bestDistance=Infinity;for(const bat of this.agents){if(!bat.active)continue;const t=THREE.MathUtils.clamp(bat.position.clone().sub(from).dot(segment)/Math.max(.001,lengthSq),0,1);const point=from.clone().addScaledVector(segment,t);const distance=point.distanceTo(bat.position);if(distance<radius&&distance<bestDistance){best=bat;bestDistance=distance;}}if(best){best.active=false;best.captured=true;this.events.emit('bat-captured',{bat:best,position:best.position.clone()});}return best;}
  activeCount(){return this.agents.filter((bat)=>bat.active).length;}
  dispose(){this.unsubscribe();for(const mesh of [this.bodies,this.wings,this.heatBodies,this.heatWings]){this.scene.remove(mesh);mesh.geometry.dispose();mesh.material.dispose();}}
}
