// @ts-check
import * as THREE from 'three';
import { BatAgent } from './BatAgent.js';
import { markHeat } from '../../sensory/HeatSignature.js';
import { Random } from '../../core/Random.js';
import { FlightRouteNetwork } from '../../world/FlightRouteNetwork.js';

export class BatFlock {
  constructor(scene,count,events,options={}){this.scene=scene;this.count=count;this.events=events;this.random=options.random||new Random('fallback-flock');this.routes=options.routes||new FlightRouteNetwork();this.director=options.director||{density:1,panic:1,routeOccupancy:{central:0,high:0,lower:0,shelf:0,arc:0},recordOccupancy(){},routeWeight(){return 1;},disturb(){}};this.agents=Array.from({length:count},(_,i)=>new BatAgent(i,this.random.fork(`bat-${i}`),this.routes,this.director));this.elapsed=0;this.occupancy={central:0,high:0,lower:0,shelf:0,arc:0};this.panicCount=0;this.forwardAxis=new THREE.Vector3(0,0,1);this.desired=new THREE.Vector3();this.routeTarget=new THREE.Vector3();this.offset=new THREE.Vector3();this.directionTemp=new THREE.Vector3();this.positionTemp=new THREE.Vector3();this.quaternion=new THREE.Quaternion();this.bodyMatrix=new THREE.Matrix4();this.wingMatrix=new THREE.Matrix4();this.featureMatrix=new THREE.Matrix4();this.scale=new THREE.Vector3();this.unitScale=new THREE.Vector3(1,1,1);this.captureSegment=new THREE.Vector3();this.capturePoint=new THREE.Vector3();this.color=new THREE.Color();this.buildMeshes();this.unsubscribe=[events.on('echolocation-pulse',({origin,range,kind})=>this.startle(origin,range,kind==='full'?1:.45)),events.on('snake-strike-started',({controller})=>this.danger(controller.headPosition,1)),events.on('player-collision',({position})=>this.danger(position,.65))];}
  buildMeshes(){const bodyGeo=new THREE.CapsuleGeometry(.14,.38,3,7);bodyGeo.rotateX(Math.PI/2);const headGeo=new THREE.SphereGeometry(.13,7,5);headGeo.scale(1,.78,1.15);const rootGeo=new THREE.SphereGeometry(.11,6,4);const wingGeo=new THREE.BufferGeometry();wingGeo.setAttribute('position',new THREE.Float32BufferAttribute([0,0,0,-.72,.08,-.05,-.48,-.02,.22,-.18,-.06,.32,0,0,0,.72,.08,-.05,.48,-.02,.22,.18,-.06,.32],3));wingGeo.setIndex([0,1,2,0,2,3,4,5,6,4,6,7]);wingGeo.computeVertexNormals();const bodyMat=new THREE.MeshStandardMaterial({color:0x211915,roughness:.9}),wingMat=new THREE.MeshPhysicalMaterial({color:0x2e201b,roughness:.82,transparent:true,opacity:.68,side:THREE.DoubleSide,transmission:.06});this.bodies=new THREE.InstancedMesh(bodyGeo,bodyMat,this.count);this.heads=new THREE.InstancedMesh(headGeo,bodyMat,this.count);this.wings=new THREE.InstancedMesh(wingGeo,wingMat,this.count);this.bodies.castShadow=this.heads.castShadow=this.wings.castShadow=true;this.scene.add(this.bodies,this.heads,this.wings);const coreMat=new THREE.MeshBasicMaterial({color:0xffffff,vertexColors:true,transparent:true,opacity:.92,depthWrite:false,depthTest:true,blending:THREE.AdditiveBlending,fog:true}),membraneMat=new THREE.MeshBasicMaterial({color:0xffffff,vertexColors:true,transparent:true,opacity:.44,side:THREE.DoubleSide,depthWrite:false,depthTest:true,blending:THREE.AdditiveBlending,fog:true});this.heatBodies=new THREE.InstancedMesh(bodyGeo,coreMat,this.count);this.heatHeads=new THREE.InstancedMesh(headGeo,coreMat,this.count);this.heatRoots=new THREE.InstancedMesh(rootGeo,coreMat,this.count*2);this.heatWings=new THREE.InstancedMesh(wingGeo,membraneMat,this.count);markHeat(this.heatBodies,'torso',.92);markHeat(this.heatHeads,'head',1);markHeat(this.heatRoots,'wingRoot',.84);markHeat(this.heatWings,'membrane',.46);this.scene.add(this.heatBodies,this.heatHeads,this.heatRoots,this.heatWings);}
  startle(origin,range,force=1){for(const bat of this.agents){const distance=bat.position.distanceTo(origin);if(distance<range){bat.panic=Math.max(bat.panic,(1-distance/range)*force*bat.role.panic*this.director.panic);bat.recentDanger=1;}}this.director.disturb(force);}
  danger(position,force){this.startle(position,10,force);}
  update(dt,playerPosition,snakes=[]){this.elapsed+=dt;this.panicCount=0;this.routes.occupancy(this.agents,this.occupancy);this.director.recordOccupancy(this.occupancy);for(const bat of this.agents){bat.departureDelay-=dt;bat.routeSwitchCooldown=Math.max(0,bat.routeSwitchCooldown-dt);bat.recentDanger=Math.max(0,bat.recentDanger-dt*.3);if(bat.departureDelay>0||!bat.active){this.bodyMatrix.makeScale(0,0,0);this.setMatrices(bat.index,this.bodyMatrix);continue;}bat.panic=Math.max(0,bat.panic-dt*.25);if(bat.panic>.25)this.panicCount++;if(bat.recentDanger>.2&&bat.routeSwitchCooldown<=0&&bat.random.chance(dt*(.7+bat.panic))){bat.routeId=this.routes.choose(bat.random,this.director,bat.role,bat.routeId).id;bat.routeSwitchCooldown=2+bat.random.range(0,3);}const route=this.routes.get(bat.routeId);this.routes.sample(bat.routeId,bat.position.z+4,this.routeTarget);const lateral=Math.sin(bat.position.z*.1+bat.phase)*route.width*.35;this.desired.subVectors(this.routeTarget,bat.position).normalize().multiplyScalar(8.1*route.speed*bat.role.speed+bat.panic*4.2);this.desired.x+=lateral;for(const other of this.agents){if(other===bat||!other.active)continue;const d=bat.position.distanceToSquared(other.position);if(d<1.5&&d>.001)this.desired.addScaledVector(this.offset.subVectors(bat.position,other.position).normalize(),(1.5-d)*bat.role.separation);}for(const snake of snakes){const d=bat.position.distanceTo(snake.position);if(d<9&&snake.state!=='recover'){this.desired.addScaledVector(this.offset.subVectors(bat.position,snake.position).normalize(),(9-d)*1.35);bat.recentDanger=Math.max(bat.recentDanger,.5);}}if(playerPosition){const d=bat.position.distanceTo(playerPosition);if(d<2.4){this.desired.addScaledVector(this.offset.subVectors(bat.position,playerPosition).normalize(),(2.4-d)*1.2);if(d<1.1)bat.panic=Math.max(bat.panic,.3*bat.role.panic);}}bat.velocity.lerp(this.desired,Math.min(1,dt*(1.05+bat.panic*2)));bat.position.addScaledVector(bat.velocity,dt);if(bat.position.z>55)bat.recycle(this.routes,this.director);this.updateVisual(bat);}
    for(const mesh of [this.bodies,this.heads,this.wings,this.heatBodies,this.heatHeads,this.heatRoots,this.heatWings])mesh.instanceMatrix.needsUpdate=true;for(const mesh of [this.heatBodies,this.heatHeads,this.heatRoots,this.heatWings])if(mesh.instanceColor)mesh.instanceColor.needsUpdate=true;}
  updateVisual(bat){const flap=Math.sin(this.elapsed*(11+bat.panic*8)+bat.phase);this.quaternion.setFromUnitVectors(this.forwardAxis,this.directionTemp.copy(bat.velocity).normalize());this.bodyMatrix.compose(bat.position,this.quaternion,this.unitScale);this.bodies.setMatrixAt(bat.index,this.bodyMatrix);this.heatBodies.setMatrixAt(bat.index,this.bodyMatrix);this.positionTemp.copy(bat.position).add(this.offset.set(0,.02,.3).applyQuaternion(this.quaternion));this.featureMatrix.compose(this.positionTemp,this.quaternion,this.unitScale);this.heads.setMatrixAt(bat.index,this.featureMatrix);this.heatHeads.setMatrixAt(bat.index,this.featureMatrix);this.scale.set(1,Math.max(.18,.72+.52*flap),1);this.wingMatrix.compose(bat.position,this.quaternion,this.scale);this.wings.setMatrixAt(bat.index,this.wingMatrix);this.heatWings.setMatrixAt(bat.index,this.wingMatrix);for(let side=0;side<2;side++){this.positionTemp.copy(bat.position).add(this.offset.set(side?-.22:.22,0,.02).applyQuaternion(this.quaternion));this.featureMatrix.compose(this.positionTemp,this.quaternion,this.unitScale);this.heatRoots.setMatrixAt(bat.index*2+side,this.featureMatrix);}const activity=THREE.MathUtils.clamp(.64+bat.velocity.length()*.022+bat.panic*.22+Math.max(0,flap)*.08,0,1);this.heatBodies.setColorAt(bat.index,this.color.setRGB(1,.33+.38*activity,.08));this.heatHeads.setColorAt(bat.index,this.color.setRGB(1,.58+.28*activity,.18));this.heatWings.setColorAt(bat.index,this.color.setRGB(.56+.24*activity,.12+.16*activity,.045));this.heatRoots.setColorAt(bat.index*2,this.color.setRGB(1,.42+.34*activity,.09));this.heatRoots.setColorAt(bat.index*2+1,this.color);}
  setMatrices(index,matrix){this.bodies.setMatrixAt(index,matrix);this.heads.setMatrixAt(index,matrix);this.wings.setMatrixAt(index,matrix);this.heatBodies.setMatrixAt(index,matrix);this.heatHeads.setMatrixAt(index,matrix);this.heatWings.setMatrixAt(index,matrix);this.heatRoots.setMatrixAt(index*2,matrix);this.heatRoots.setMatrixAt(index*2+1,matrix);}
  captureAlong(from,to,radius){this.captureSegment.subVectors(to,from);const lengthSquared=this.captureSegment.lengthSq();let best=null,bestDistance=Infinity;for(const bat of this.agents){if(!bat.active)continue;const t=THREE.MathUtils.clamp(this.offset.subVectors(bat.position,from).dot(this.captureSegment)/Math.max(.001,lengthSquared),0,1);this.capturePoint.copy(from).addScaledVector(this.captureSegment,t);const d=this.capturePoint.distanceTo(bat.position);if(d<radius&&d<bestDistance){best=bat;bestDistance=d;}}if(best){best.active=false;best.captured=true;this.events.emit('bat-captured',{bat:best,position:best.position.clone(),route:best.routeId});}return best;}
  activeCount(){let count=0;for(const bat of this.agents)if(bat.active&&bat.departureDelay<=0)count++;return count;}heatSources(){return this.agents;}routeOccupancy(){return this.occupancy;}dispose(){this.unsubscribe.forEach(fn=>fn());for(const mesh of [this.bodies,this.heads,this.wings,this.heatBodies,this.heatHeads,this.heatRoots,this.heatWings]){this.scene.remove(mesh);mesh.geometry.dispose();mesh.material.dispose();}}
}
