// @ts-check
import * as THREE from 'three';

function wingGeometry(side){const s=side;const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute([0,0,0,s*.58,.02,-.08,s*1.18,-.12,.08,s*.92,-.58,.16,s*.34,-.4,.06,0,0,0],3));geometry.setIndex([0,1,4,1,2,3,1,3,4,0,4,5]);geometry.computeVertexNormals();return geometry;}

export class BatFirstPersonRig {
  /** @param {THREE.PerspectiveCamera} camera @param {import('./BatFlightController.js').BatFlightController} controller @param {import('../../core/InputManager.js').InputManager} input @param {import('../../core/EventBus.js').EventBus} events @param {import('../../core/Settings.js').Settings} settings */
  constructor(camera,controller,input,events,settings){this.camera=camera;this.controller=controller;this.input=input;this.events=events;this.settings=settings;this.root=new THREE.Group();this.root.name='First-person bat visual adapter';this.root.position.set(0,-.1,-.48);camera.add(this.root);const membrane=new THREE.MeshPhysicalMaterial({color:0x54372f,emissive:0x160b08,emissiveIntensity:.72,roughness:.72,transparent:true,opacity:.82,side:THREE.DoubleSide,transmission:.05,thickness:.03});const boneMaterial=new THREE.MeshStandardMaterial({color:0x49362d,emissive:0x100908,emissiveIntensity:.45,roughness:.9});this.wings=[];for(const side of [-1,1]){const shoulder=new THREE.Group();shoulder.position.x=side*.13;const wing=new THREE.Mesh(wingGeometry(side),membrane);wing.renderOrder=1;const forearm=new THREE.Mesh(new THREE.CylinderGeometry(.018,.026,.78,6),boneMaterial);forearm.rotation.z=side*Math.PI*.42;forearm.position.set(side*.28,-.2,.02);shoulder.add(wing,forearm);this.root.add(shoulder);this.wings.push(shoulder);}this.claws=[];for(const side of [-1,1]){const claw=new THREE.Mesh(new THREE.TorusGeometry(.055,.009,4,8,Math.PI*.72),boneMaterial);claw.position.set(side*.28,-.28,.02);claw.rotation.set(Math.PI*.5,0,side*.45);this.root.add(claw);this.claws.push(claw);}this.phase=0;this.panic=0;this.collision=0;this.unsubscribe=[events.on('player-collision',()=>{this.collision=1;}),events.on('near-miss',()=>{this.panic=1;})];}
  update(dt){const c=this.controller;const flap=this.input.down('Space')||c.flapTimer>.08,brake=this.input.down('KeyS'),dive=this.input.down('ShiftLeft')||this.input.down('ShiftRight');const speed=c.velocity.length();this.phase+=dt*(flap?15:brake?5:7+speed*.35);this.panic=Math.max(0,this.panic-dt*1.45);this.collision=Math.max(0,this.collision-dt*1.8);const glideAmount=flap ? 1 : brake ? .42 : .18;const stroke=flap?Math.sin(this.phase)*.68:Math.sin(this.phase*.42)*.08;const bank=THREE.MathUtils.clamp(c.bank,-.75,.75);const disrupted=Math.sin(this.phase*2.7)*this.collision*.34+Math.sin(this.phase*2.1)*this.panic*.18;for(let index=0;index<2;index++){const side=index===0?-1:1;const wing=this.wings[index];const asymmetric=bank*side*.28;wing.rotation.x=stroke*glideAmount+disrupted*side+(dive ? .24 : 0);wing.rotation.y=side*(-.12-(brake ? .22 : 0))+asymmetric;wing.rotation.z=side*(brake ? .16 : .02)-bank*.15;wing.position.y=(brake?-.04:.04)+Math.abs(stroke)*.035;const claw=this.claws[index];claw.visible=brake||this.collision>.25;claw.rotation.z=side*(.2+(brake ? .35 : 0));}const motion=this.settings.get('reducedCameraMotion') ? .35 : 1;this.root.rotation.z=-bank*.2*motion;this.root.rotation.x=(dive ? .16 : brake ? -.12 : 0)*motion+this.collision*.06*Math.sin(this.phase*3);this.root.position.y=-.1-Math.abs(stroke)*.018*motion;this.root.visible=true;}
  getWingState(){return {left:this.wings[0].rotation,right:this.wings[1].rotation,panic:this.panic,collision:this.collision};}
  dispose(){this.unsubscribe.forEach((unsubscribe)=>unsubscribe());this.camera.remove(this.root);this.root.traverse((object)=>{if(object.isMesh){object.geometry.dispose();object.material.dispose();}});}
}
