// @ts-check
import * as THREE from 'three';
export class AudioManager {
  /** @param {import('../core/Settings.js').Settings} settings @param {import('../core/EventBus.js').EventBus} events */
  constructor(settings,events){this.settings=settings;this.events=events;/** @type {AudioContext|null} */this.context=null;this.master=null;this.buses={};this.enabled=false;this.ambienceSource=null;this.listenerForward=new THREE.Vector3();this.unsubscribers=[events.on('echolocation-pulse',({origin,reflections=[]})=>this.chirp(origin,reflections)),events.on('bat-flap',({position})=>this.flap(position)),events.on('snake-strike-started',({controller})=>this.strike(controller.headPosition)),events.on('bat-captured',({position})=>this.capture(position)),events.on('player-collision',({position})=>this.impact(position))];}
  async init(){if(this.context){if(this.context.state==='suspended')await this.context.resume();return;}try{const AudioCtor=window.AudioContext||window.webkitAudioContext;if(!AudioCtor)throw new Error('Web Audio API unavailable');this.context=new AudioCtor();this.master=this.context.createGain();this.master.connect(this.context.destination);for(const name of ['effects','ambience','creatures']){const gain=this.context.createGain();gain.connect(this.master);this.buses[name]=gain;}this.applyVolumes();this.startAmbience();this.enabled=true;}catch(error){this.enabled=false;this.events.emit('notice',{message:'Audio could not start; the hunt will continue silently.'});console.warn('Batsnake audio unavailable',error);}}
  applyVolumes(){if(!this.context||!this.master)return;const now=this.context.currentTime;this.master.gain.setTargetAtTime(this.settings.get('masterVolume'),now,.02);this.buses.effects?.gain.setTargetAtTime(this.settings.get('effectsVolume'),now,.02);this.buses.creatures?.gain.setTargetAtTime(this.settings.get('effectsVolume'),now,.02);this.buses.ambience?.gain.setTargetAtTime(this.settings.get('ambienceVolume')*.22,now,.04);}
  startAmbience(){if(!this.context)return;const length=this.context.sampleRate*3,buffer=this.context.createBuffer(2,length,this.context.sampleRate);for(let channel=0;channel<2;channel++){const data=buffer.getChannelData(channel);let filtered=0;for(let i=0;i<length;i++){filtered=filtered*.997+(Math.random()*2-1)*.003;data[i]=filtered*.8+Math.sin(i/this.context.sampleRate*Math.PI*2*(38+channel*3))*.015;}}const source=this.context.createBufferSource();source.buffer=buffer;source.loop=true;const filter=this.context.createBiquadFilter();filter.type='lowpass';filter.frequency.value=340;source.connect(filter).connect(this.buses.ambience);source.start();this.ambienceSource=source;}
  /** @param {{x:number,y:number,z:number}} position @param {number} frequency @param {number} duration @param {string} type @param {number} volume @param {'effects'|'creatures'} bus */
  tone(position,frequency,duration,type='sine',volume=.1,bus='effects'){if(!this.context||!this.enabled)return;const now=this.context.currentTime,osc=this.context.createOscillator(),gain=this.context.createGain(),panner=this.context.createPanner();panner.panningModel='HRTF';panner.distanceModel='inverse';panner.refDistance=3;panner.maxDistance=55;panner.positionX.value=position.x;panner.positionY.value=position.y;panner.positionZ.value=position.z;osc.type=type;osc.frequency.setValueAtTime(frequency,now);osc.frequency.exponentialRampToValueAtTime(Math.max(25,frequency*.55),now+duration);gain.gain.setValueAtTime(.001,now);gain.gain.exponentialRampToValueAtTime(volume,now+.008);gain.gain.exponentialRampToValueAtTime(.001,now+duration);osc.connect(gain).connect(panner).connect(this.buses[bus]);osc.start(now);osc.stop(now+duration+.02);}
  chirp(position,reflections=[]){this.tone(position,760,.16,'sine',.15,'effects');const frequencies={wall:390,floor:305,column:455,shelf:340,stalactite:510,mouth:250,snake:185};for(const reflection of reflections.slice(0,10)){const delay=Math.min(1500,55+reflection.distance/21.5*1000);const frequency=frequencies[reflection.kind]||360;setTimeout(()=>this.tone(reflection.position,frequency,.18+reflection.strength*.22,reflection.kind==='snake'?'triangle':'sine',.018+reflection.strength*.032,reflection.kind==='snake'?'creatures':'effects'),delay);}}
  flap(position){this.tone(position,92,.08,'triangle',.035,'creatures');}
  strike(position){this.tone(position,145,.18,'sawtooth',.12,'creatures');}
  capture(position){this.tone(position,118,.45,'triangle',.16,'creatures');this.tone(position,54,.6,'sine',.12,'creatures');}
  impact(position){this.tone(position,76,.24,'square',.08,'effects');}
  updateListener(camera){if(!this.context)return;const listener=this.context.listener,forward=this.listenerForward;camera.getWorldDirection(forward);listener.positionX.value=camera.position.x;listener.positionY.value=camera.position.y;listener.positionZ.value=camera.position.z;listener.forwardX.value=forward.x;listener.forwardY.value=forward.y;listener.forwardZ.value=forward.z;listener.upX.value=0;listener.upY.value=1;listener.upZ.value=0;}
  dispose(){this.unsubscribers.forEach((unsubscribe)=>unsubscribe());this.ambienceSource?.stop();this.context?.close();}
}
