// @ts-check
import * as THREE from 'three';
export class AudioManager {
  /** @param {import('../core/Settings.js').Settings} settings @param {import('../core/EventBus.js').EventBus} events */
  constructor(settings,events){this.settings=settings;this.events=events;/** @type {AudioContext|null} */this.context=null;this.master=null;this.buses={};this.enabled=false;this.ambienceSource=null;this.ambienceLfo=null;this.noiseBuffer=null;this.deferred=new Set();this.listenerForward=new THREE.Vector3();this.lastBreath=0;this.lastTension=0;this.unsubscribers=[events.on('echolocation-pulse',({origin,reflections=[],kind='full'})=>this.chirp(origin,reflections,kind)),events.on('bat-flap',({position,effort=.75})=>this.flap(position,effort)),events.on('snake-strike-started',({controller})=>this.strike(controller.headPosition)),events.on('strike-missed',({position,reason})=>this.strikeMiss(position,reason)),events.on('bat-captured',({position})=>this.capture(position)),events.on('player-collision',({position})=>this.impact(position)),events.on('airflow-changed',({strength})=>{if(this.buses.ambience&&this.context)this.buses.ambience.gain.setTargetAtTime(this.settings.get('ambienceVolume')*(.18+strength*.09),this.context.currentTime,.4);})];}
  async init(){if(this.context){if(this.context.state==='suspended')await this.context.resume();return;}try{const AudioCtor=window.AudioContext||window.webkitAudioContext;if(!AudioCtor)throw new Error('Web Audio API unavailable');this.context=new AudioCtor();this.master=this.context.createGain();this.master.connect(this.context.destination);for(const name of ['effects','ambience','creatures']){const gain=this.context.createGain();gain.connect(this.master);this.buses[name]=gain;}this.applyVolumes();this.makeNoise();this.startAmbience();this.enabled=true;}catch(error){this.enabled=false;this.events.emit('notice',{message:'Audio could not start; the hunt will continue silently.'});console.warn('Batsnake audio unavailable',error);}}
  applyVolumes(){if(!this.context||!this.master)return;const now=this.context.currentTime;this.master.gain.setTargetAtTime(this.settings.get('masterVolume'),now,.02);this.buses.effects?.gain.setTargetAtTime(this.settings.get('effectsVolume'),now,.02);this.buses.creatures?.gain.setTargetAtTime(this.settings.get('effectsVolume'),now,.02);this.buses.ambience?.gain.setTargetAtTime(this.settings.get('ambienceVolume')*.22,now,.04);}
  makeNoise(){const length=this.context.sampleRate*2;this.noiseBuffer=this.context.createBuffer(1,length,this.context.sampleRate);const data=this.noiseBuffer.getChannelData(0);for(let i=0;i<length;i++)data[i]=Math.random()*2-1;}
  startAmbience(){if(!this.context)return;const seconds=16,length=this.context.sampleRate*seconds,buffer=this.context.createBuffer(2,length,this.context.sampleRate);for(let channel=0;channel<2;channel++){const data=buffer.getChannelData(channel);let filtered=0;for(let i=0;i<length;i++){const t=i/this.context.sampleRate;filtered=filtered*.997+(Math.random()*2-1)*.003;const swell=.75+.25*Math.sin(t*.55+channel*2.1)+.12*Math.sin(t*1.7+channel);data[i]=filtered*.8*swell+Math.sin(t*Math.PI*2*(36+channel*3))*.014*(0.6+.4*Math.sin(t*.31));}}const source=this.context.createBufferSource();source.buffer=buffer;source.loop=true;const filter=this.context.createBiquadFilter();filter.type='lowpass';filter.frequency.value=330;filter.Q.value=.4;const lfo=this.context.createOscillator();lfo.frequency.value=.07;const lfoGain=this.context.createGain();lfoGain.gain.value=60;lfo.connect(lfoGain).connect(filter.frequency);lfo.start();source.connect(filter).connect(this.buses.ambience);source.start();this.ambienceSource=source;this.ambienceLfo=lfo;}
  /** @param {{x:number,y:number,z:number}} position @param {number} frequency @param {number} duration @param {string} type @param {number} volume @param {'effects'|'creatures'} bus */
  tone(position,frequency,duration,type='sine',volume=.1,bus='effects',glideTo=null){if(!this.context||!this.enabled)return;const now=this.context.currentTime,osc=this.context.createOscillator(),gain=this.context.createGain(),panner=this.context.createPanner();panner.panningModel='HRTF';panner.distanceModel='inverse';panner.refDistance=3;panner.maxDistance=55;panner.positionX.value=position.x;panner.positionY.value=position.y;panner.positionZ.value=position.z;osc.type=type;osc.frequency.setValueAtTime(frequency,now);osc.frequency.exponentialRampToValueAtTime(Math.max(25,glideTo??frequency*.55),now+duration);gain.gain.setValueAtTime(.001,now);gain.gain.exponentialRampToValueAtTime(volume,now+.008);gain.gain.exponentialRampToValueAtTime(.001,now+duration);osc.connect(gain).connect(panner).connect(this.buses[bus]);osc.start(now);osc.stop(now+duration+.02);}
  /** Filtered noise burst: wingbeats, scale drag, breath, airflow. */
  whoosh(position,frequency,q,duration,volume,bus='creatures',delay=0){if(!this.context||!this.enabled)return;const now=this.context.currentTime+delay,source=this.context.createBufferSource();source.buffer=this.noiseBuffer;const filter=this.context.createBiquadFilter();filter.type='bandpass';filter.frequency.setValueAtTime(frequency,now);filter.frequency.exponentialRampToValueAtTime(Math.max(60,frequency*.5),now+duration);filter.Q.value=q;const gain=this.context.createGain();gain.gain.setValueAtTime(.001,now);gain.gain.exponentialRampToValueAtTime(volume,now+.02);gain.gain.exponentialRampToValueAtTime(.001,now+duration);const panner=this.context.createPanner();panner.panningModel='HRTF';panner.distanceModel='inverse';panner.refDistance=3;panner.maxDistance=55;panner.positionX.value=position.x;panner.positionY.value=position.y;panner.positionZ.value=position.z;source.connect(filter).connect(gain).connect(panner).connect(this.buses[bus]);source.start(now);source.stop(now+duration+.05);}
  chirp(position,reflections=[],kind='full'){this.tone(position,kind==='quick'?980:650,kind==='quick'?.09:.2,'sine',kind==='quick'?.09:.16,'effects');if(kind==='full')this.tone(position,54,.5,'sine',.11,'effects',42);const frequencies={wall:390,floor:305,column:455,shelf:340,stalactite:510,mouth:250,snake:185};for(const reflection of reflections.slice(0,kind==='quick'?5:10)){const delay=Math.min(1500,55+reflection.distance/21.5*1000);const frequency=frequencies[reflection.kind]||360;const timer=setTimeout(()=>{this.deferred.delete(timer);this.tone(reflection.position,frequency,.18+reflection.strength*.22,reflection.kind==='snake'?'triangle':'sine',.018+reflection.strength*.032,reflection.kind==='snake'?'creatures':'effects');},delay);this.deferred.add(timer);}}
  /** Wing transient scales with flight effort: a soft glide puff or a hard reserve-powered beat. */
  flap(position,effort=.75){const power=THREE.MathUtils.clamp(effort,.25,1);this.whoosh(position,750+power*250,1.1,.09,.014+power*.03);this.tone(position,88+power*30,.075,'triangle',.02+power*.028,'creatures',70);}
  strike(position){this.whoosh(position,1300,2.2,.22,.1);this.tone(position,145,.18,'sawtooth',.1,'creatures',90);}
  strikeMiss(position,reason){if(reason==='obstruction'){this.impact(position);this.whoosh(position,300,1,.3,.05,'creatures',.12);}else if(reason==='overreach'){this.tone(position,150,.34,'sine',.05,'creatures',64);}else{this.whoosh(position,950,1.4,.2,.045);}this.whoosh(position,420,.8,.42,.028,'creatures',.32);}
  capture(position){this.tone(position,118,.45,'triangle',.16,'creatures');this.tone(position,54,.6,'sine',.12,'creatures');this.whoosh(position,2400,1.6,.28,.05,'creatures',.05);this.whoosh(position,380,.9,.5,.03,'creatures',.4);}
  impact(position){this.tone(position,76,.24,'square',.08,'effects');this.whoosh(position,500,1.2,.16,.05,'effects');}
  /** Close boa breath: a slow cold exhale when the player bat is near a post. */
  breath(position){const now=performance.now();if(now-this.lastBreath<2100)return;this.lastBreath=now;this.whoosh(position,210,.7,1.5,.03);}
  /** Muscle tension while a strike charges; call at most ~8 Hz with the current charge. */
  tension(position,charge){const now=performance.now();if(now-this.lastTension<130)return;this.lastTension=now;this.tone(position,52+charge*36,.14,'sawtooth',.012+charge*.03,'creatures',58+charge*40);}
  updateListener(camera){if(!this.context)return;const listener=this.context.listener,forward=this.listenerForward;camera.getWorldDirection(forward);listener.positionX.value=camera.position.x;listener.positionY.value=camera.position.y;listener.positionZ.value=camera.position.z;listener.forwardX.value=forward.x;listener.forwardY.value=forward.y;listener.forwardZ.value=forward.z;listener.upX.value=0;listener.upY.value=1;listener.upZ.value=0;}
  dispose(){this.unsubscribers.forEach((unsubscribe)=>unsubscribe());for(const timer of this.deferred)clearTimeout(timer);this.deferred.clear();this.ambienceSource?.stop();this.ambienceLfo?.stop();this.context?.close();}
}
