// @ts-check
import * as THREE from 'three';
import RAPIER from '@dimforge/rapier3d';
import { EventBus } from './EventBus.js';
import { Settings } from './Settings.js';
import { GameState, GamePhase } from './GameState.js';
import { InputManager } from './InputManager.js';
import { AssetManager } from './AssetManager.js';
import { GameLoop } from './GameLoop.js';
import { CaveWorld } from '../world/CaveWorld.js';
import { CaveFog } from '../effects/CaveFog.js';
import { DustParticles } from '../effects/DustParticles.js';
import { DripParticles } from '../effects/DripParticles.js';
import { ImpactEffects } from '../effects/ImpactEffects.js';
import { MotionEffects } from '../effects/MotionEffects.js';
import { PostProcessing } from '../effects/PostProcessing.js';
import { AudioManager } from '../audio/AudioManager.js';
import { CaveAmbience } from '../audio/CaveAmbience.js';
import { MainMenu } from '../ui/MainMenu.js';
import { SettingsMenu } from '../ui/SettingsMenu.js';
import { BatHUD } from '../ui/BatHUD.js';
import { SnakeHUD } from '../ui/SnakeHUD.js';
import { EndScreen } from '../ui/EndScreen.js';
import { PerformanceOverlay } from '../ui/PerformanceOverlay.js';
import { BatMode } from '../gameplay/BatMode.js';
import { SnakeMode } from '../gameplay/SnakeMode.js';

export class App {
  constructor(){this.canvas=/** @type {HTMLCanvasElement} */(document.getElementById('game-canvas'));this.uiRoot=/** @type {HTMLElement} */(document.getElementById('ui-root'));this.events=new EventBus();this.settings=new Settings();this.state=new GameState();this.assets=new AssetManager(this.events);this.mode=null;this.menuTime=0;this.toastTimer=0;}
  async init(){this.progress('Surveying the chamber…',.22);const context=this.canvas.getContext('webgl2',{antialias:true,alpha:false,powerPreference:'high-performance'});if(!context)throw new Error('WebGL2 is unavailable. Batsnake needs a current desktop browser with hardware acceleration enabled.');this.renderer=new THREE.WebGLRenderer({canvas:this.canvas,context,antialias:true,powerPreference:'high-performance'});this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=.82;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFShadowMap;this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.08,150);this.camera.position.set(7,5,-18);this.camera.lookAt(0,4,8);this.applyResolution();this.progress('Waking the physics field…',.46);try{await RAPIER.init({});}catch(error){throw new Error(`Rapier WASM failed to initialize. Confirm vendor files are present and the game is served over HTTP. ${error instanceof Error?error.message:''}`);}this.world=new CaveWorld(this.scene,this.settings.profile());this.fog=new CaveFog(this.scene);this.dust=new DustParticles(this.scene,300);this.drips=new DripParticles(this.scene);this.impacts=new ImpactEffects(this.scene);this.motion=new MotionEffects(this.camera,this.settings);this.post=new PostProcessing(this.renderer,this.scene,this.camera,this.settings.profile());this.input=new InputManager(this.canvas,this.events);this.audio=new AudioManager(this.settings,this.events);this.ambience=new CaveAmbience(this.audio);this.progress('Listening for wings…',.75);this.buildUI();this.bindEvents();this.onResize();window.addEventListener('resize',()=>this.onResize());this.loop=new GameLoop(this);this.state.setPhase(GamePhase.MENU);this.progress('Field station ready',1);setTimeout(()=>document.getElementById('loading')?.classList.add('hidden'),350);this.loop.start();}
  buildUI(){this.mainMenu=new MainMenu(this.uiRoot,{onPlay:(mode)=>this.startMode(mode),onSettings:()=>this.settingsMenu.show(),onNotes:()=>this.showNotes()});this.settingsMenu=new SettingsMenu(this.uiRoot,this.settings,this.events);this.batHUD=new BatHUD(this.uiRoot);this.snakeHUD=new SnakeHUD(this.uiRoot);this.endScreen=new EndScreen(this.uiRoot,{restart:()=>this.restart(),menu:()=>this.returnToMenu()});this.pauseScreen=document.createElement('section');this.pauseScreen.className='pause-card hidden';this.pauseScreen.innerHTML='<div class="end-sheet"><p class="eyebrow">Observation paused</p><h2>The cave waits</h2><p>Click resume to return to the animal.</p><div class="end-actions"><button data-action="resume">Resume</button><button data-action="menu">Leave run</button></div></div>';this.uiRoot.append(this.pauseScreen);this.pauseScreen.querySelector('[data-action=resume]')?.addEventListener('click',()=>this.resume());this.pauseScreen.querySelector('[data-action=menu]')?.addEventListener('click',()=>this.returnToMenu());this.performance=new PerformanceOverlay(/** @type {HTMLElement} */(document.getElementById('performance')),this.settings);}
  bindEvents(){this.events.on('notice',({message})=>this.toast(message));this.events.on('asset-error',({url,required})=>this.toast(`${required?'Required':'Optional'} field asset missing: ${url}`));this.events.on('settings-changed',({key})=>{if(key==='quality'||key==='resolutionScale'){this.applyResolution();this.world.setQuality(this.settings.profile());this.post.setQuality(this.settings.profile());this.dust.setCount(this.settings.profile().particles);if(key==='quality'&&this.mode)this.toast('Render profile changed. Flock density updates next run.');}if(key.includes('Volume'))this.audio.applyVolumes();});this.events.on('player-collision',({position})=>this.impacts.burst(position,0xa7cbbf));this.events.on('near-miss',({position})=>this.impacts.burst(position,0xd88b62));this.events.on('pointer-lock',({locked})=>{if(!locked&&this.state.isPlaying())this.pause();});}
  async startMode(mode){await this.audio.init();this.mainMenu.hide();this.endScreen.hide();this.pauseScreen.classList.add('hidden');this.disposeMode();this.state.begin(mode);const context={scene:this.scene,camera:this.camera,input:this.input,settings:this.settings,world:this.world,events:this.events,fog:this.fog,onEnd:(result)=>this.endRun(result)};this.mode=mode==='bat'?new BatMode({...context,hud:this.batHUD}):new SnakeMode({...context,hud:this.snakeHUD});this.input.requestLock();this.toast(mode==='bat'?'Follow the moonlight. Darkness returns after each call.':'Heat lives in motion. Hold, lead, release.');}
  endRun(result){this.state.setPhase(GamePhase.ENDED);this.input.releaseLock();this.endScreen.show(result);}
  restart(){const mode=this.state.mode;if(mode)this.startMode(mode);}
  returnToMenu(){this.disposeMode();this.state.setPhase(GamePhase.MENU);this.state.mode=null;this.input.releaseLock();this.endScreen.hide();this.pauseScreen.classList.add('hidden');this.mainMenu.show();this.fog.setThermal(false);this.camera.fov=72;this.camera.updateProjectionMatrix();}
  pause(){if(!this.state.isPlaying())return;this.state.setPhase(GamePhase.PAUSED);this.pauseScreen.classList.remove('hidden');}
  resume(){if(this.state.phase!==GamePhase.PAUSED)return;this.state.setPhase(GamePhase.PLAYING);this.pauseScreen.classList.add('hidden');this.input.requestLock();}
  showNotes(){const modal=document.createElement('section');modal.className='panel-modal';modal.innerHTML='<div class="panel-sheet"><p class="eyebrow">Field notes 01</p><h2>At the flight line</h2><p>Cuban boas have been documented suspending themselves from cave ceilings to intercept bats in flight. Bats build a spatial picture from returning sound; snakes read moving warmth through specialized facial pits. Batsnake turns those two sensory worlds into complementary first-person survival systems.</p><p>This vertical slice uses procedural animals, cave geometry, materials, and synthesized sound. No finished wildlife assets are represented as documentary footage.</p><div class="panel-footer"><button class="text-button">Close notes</button></div></div>';this.uiRoot.append(modal);modal.querySelector('button')?.addEventListener('click',()=>modal.remove());}
  disposeMode(){if(this.mode){this.mode.dispose();this.mode=null;}this.batHUD?.hide();this.snakeHUD?.hide();}
  fixedUpdate(dt){if(this.state.isPlaying()){this.world.fixedUpdate();this.mode?.fixedUpdate(dt);}}
  update(dt){if(this.input.consume('Escape')){if(this.state.isPlaying())this.pause();else if(this.state.phase===GamePhase.PAUSED)this.resume();}if(this.input.consume('KeyR')&&(this.state.isPlaying()||this.state.phase===GamePhase.ENDED))this.restart();if(this.state.isPlaying())this.mode?.update(dt);else if(this.state.phase===GamePhase.MENU)this.updateMenuCamera(dt);this.dust.update(dt);this.drips.update(dt);this.impacts.update(dt,this.camera);this.ambience.update(dt,this.camera);this.audio.updateListener(this.camera);this.motion.update(dt,this.mode?.speed?.()||0);this.performance.update(dt,this.renderer,{bats:this.mode?.activeBats?.()||0,particles:this.settings.profile().particles});this.input.endFrame();}
  updateMenuCamera(dt){this.menuTime+=dt;this.camera.position.set(7+Math.sin(this.menuTime*.11)*1.7,5.5+Math.sin(this.menuTime*.17)*.35,-20+Math.cos(this.menuTime*.09)*2);this.camera.lookAt(-1,4,7);}
  render(){this.post.render();}
  applyResolution(){if(!this.renderer)return;const profile=this.settings.profile();const ratio=Math.min(2,devicePixelRatio)*profile.pixelRatio*this.settings.get('resolutionScale');this.renderer.setPixelRatio(ratio);this.renderer.setSize(innerWidth,innerHeight,false);}
  onResize(){if(!this.camera||!this.renderer)return;this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.applyResolution();this.post?.resize(innerWidth,innerHeight);}
  progress(message,value){const status=document.getElementById('loading-status'),bar=/** @type {HTMLElement|null} */(document.getElementById('load-progress'));if(status)status.textContent=message;if(bar)bar.style.width=`${value*100}%`;}
  toast(message){const element=document.getElementById('toast');if(!element)return;element.textContent=message;element.classList.add('visible');clearTimeout(this.toastTimer);this.toastTimer=window.setTimeout(()=>element.classList.remove('visible'),2800);}
}
