// @ts-check
import * as THREE from 'three';
import RAPIER from '@dimforge/rapier3d';
import { EventBus } from './EventBus.js';
import { Settings } from './Settings.js';
import { GameState, GamePhase } from './GameState.js';
import { InputManager } from './InputManager.js';
import { AssetManager } from './AssetManager.js';
import { GameLoop } from './GameLoop.js';
import { CaveWorld } from '../world/CaveWorld.js';
import { CaveFog } from '../effects/CaveFog.js';
import { DustParticles } from '../effects/DustParticles.js';
import { DripParticles } from '../effects/DripParticles.js';
import { ImpactEffects } from '../effects/ImpactEffects.js';
import { MotionEffects } from '../effects/MotionEffects.js';
import { PostProcessing } from '../effects/PostProcessing.js';
import { AudioManager } from '../audio/AudioManager.js';
import { CaveAmbience } from '../audio/CaveAmbience.js';
import { MainMenu } from '../ui/MainMenu.js';
import { SettingsMenu } from '../ui/SettingsMenu.js';
import { BatHUD } from '../ui/BatHUD.js';
import { SnakeHUD } from '../ui/SnakeHUD.js';
import { EndScreen } from '../ui/EndScreen.js';
import { PerformanceOverlay } from '../ui/PerformanceOverlay.js';
import { GameplayMenu } from '../ui/GameplayMenu.js';
import { Onboarding } from '../gameplay/Onboarding.js';
import { createSeed, normalizeSeed, randomForSeed } from '../gameplay/SessionSeed.js';
import { difficultyFor } from '../gameplay/Difficulty.js';
import { chooseEncounterProfile } from '../gameplay/EncounterProfiles.js';
import { EncounterDirector } from '../gameplay/EncounterDirector.js';
import { FlightRouteNetwork } from '../world/FlightRouteNetwork.js';
import { BatMode } from '../gameplay/BatMode.js';
import { SnakeMode } from '../gameplay/SnakeMode.js';

export class App {
  constructor(){this.canvas=/** @type {HTMLCanvasElement} */(document.getElementById('game-canvas'));this.uiRoot=/** @type {HTMLElement} */(document.getElementById('ui-root'));this.events=new EventBus();this.settings=new Settings();this.state=new GameState();this.assets=new AssetManager(this.events);this.mode=null;this.sessionSeed='';this.menuTime=0;this.toastTimer=0;}
  async init(){this.progress('Surveying the chamber…',.22);const context=this.canvas.getContext('webgl2',{antialias:true,alpha:false,powerPreference:'high-performance'});if(!context)throw new Error('WebGL2 is unavailable. Batsnake needs a current desktop browser with hardware acceleration enabled.');this.renderer=new THREE.WebGLRenderer({canvas:this.canvas,context,antialias:true,powerPreference:'high-performance'});this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=.82;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFShadowMap;this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.08,150);this.scene.add(this.camera);this.camera.position.set(7,5,-18);this.camera.lookAt(0,4,8);this.bodyLight=new THREE.PointLight(0x8c6f5d,.42,1.5,2);this.bodyLight.position.set(0,-.1,-.22);this.camera.add(this.bodyLight);this.applyResolution();this.progress('Waking the physics field…',.46);try{await RAPIER.init({});}catch(error){throw new Error(`Rapier WASM failed to initialize. Confirm vendor files are present and the game is served over HTTP. ${error instanceof Error?error.message:''}`);}this.world=new CaveWorld(this.scene,this.settings.profile());this.fog=new CaveFog(this.scene);this.dust=new DustParticles(this.scene,300);this.drips=new DripParticles(this.scene);this.impacts=new ImpactEffects(this.scene);this.motion=new MotionEffects(this.camera,this.settings);this.post=new PostProcessing(this.renderer,this.scene,this.camera,this.settings.profile());this.input=new InputManager(this.canvas,this.events);this.audio=new AudioManager(this.settings,this.events);this.ambience=new CaveAmbience(this.audio);this.progress('Listening for wings…',.75);this.buildUI();this.bindEvents();this.onResize();window.addEventListener('resize',()=>this.onResize());this.loop=new GameLoop(this);this.state.setPhase(GamePhase.MENU);this.progress('Field station ready',1);setTimeout(()=>document.getElementById('loading')?.classList.add('hidden'),350);this.loop.start();}
  buildUI(){this.gameplayMenu=new GameplayMenu(this.uiRoot,this.events,()=>this.input.activeDevice);this.mainMenu=new MainMenu(this.uiRoot,{onPlay:(mode)=>this.startMode(mode,false),onGameplay:(trigger)=>this.gameplayMenu.show(trigger),onSettings:()=>this.settingsMenu.show(),onNotes:()=>this.showNotes(),onDifficulty:(id)=>{this.settings.set('difficulty',id);this.events.emit('settings-changed',{key:'difficulty',value:id});}});this.settingsMenu=new SettingsMenu(this.uiRoot,this.settings,this.events);this.batHUD=new BatHUD(this.uiRoot);this.snakeHUD=new SnakeHUD(this.uiRoot);this.onboarding=new Onboarding(this.uiRoot,this.settings);this.endScreen=new EndScreen(this.uiRoot,{sameSeed:()=>this.restart(true),switchMode:()=>this.switchMode(),newEncounter:()=>this.restart(false),menu:()=>this.returnToMenu()});this.pauseScreen=document.createElement('section');this.pauseScreen.className='pause-card hidden';this.pauseScreen.innerHTML='<div class="end-sheet"><p class="eyebrow">Observation paused</p><h2>The cave waits</h2><p>Review the field reference or return to the animal.</p><div class="end-actions"><button data-action="resume">Resume</button><button data-action="gameplay">Gameplay</button><button data-action="menu">Leave run</button></div></div>';this.uiRoot.append(this.pauseScreen);this.pauseScreen.querySelector('[data-action=resume]')?.addEventListener('click',()=>this.resume());this.pauseScreen.querySelector('[data-action=gameplay]')?.addEventListener('click',event=>this.gameplayMenu.show(/** @type {HTMLElement} */(event.currentTarget),this.state.mode));this.pauseScreen.querySelector('[data-action=menu]')?.addEventListener('click',()=>this.returnToMenu());this.performance=new PerformanceOverlay(/** @type {HTMLElement} */(document.getElementById('performance')),this.settings);}
  bindEvents(){this.events.on('notice',({message})=>this.toast(message));this.events.on('asset-error',({url,required})=>this.toast(`${required?'Required':'Optional'} field asset missing: ${url}`));this.events.on('settings-changed',({key})=>{if(key==='quality'||key==='resolutionScale'){this.applyResolution();this.world.setQuality(this.settings.profile());this.post.setQuality(this.settings.profile());this.dust.setCount(this.settings.profile().particles);if(key==='quality'&&this.mode)this.toast('Visual profile applied; encounter state is unchanged.');}if(key.includes('Volume'))this.audio.applyVolumes();});this.events.on('player-collision',({position})=>{this.impacts.impact(position);this.input.gamepad.haptic(.55,.25,80);});this.events.on('near-miss',({position})=>{this.impacts.slipstream(position);this.input.gamepad.haptic(.5,.3,90);});this.events.on('thermal-changed',({active})=>{this.bodyLight.intensity=active ? .1 : .42;});this.events.on('bat-captured',({player})=>{if(player)this.input.gamepad.haptic(1,.6,320);});this.events.on('player-capture',()=>this.input.gamepad.haptic(.9,.5,220));this.events.on('snake-strike-started',()=>this.input.gamepad.haptic(.35,.2,70));this.events.on('snake-switched',()=>this.input.gamepad.haptic(.2,.12,45));this.events.on('pointer-lock',({locked})=>{if(!locked&&this.state.isPlaying())this.pause();});}
  async startMode(mode,reuseSeed=false,seed=null){await this.audio.init();this.mainMenu.hide();this.endScreen.hide();this.pauseScreen.classList.add('hidden');this.disposeMode();this.sessionSeed=normalizeSeed(seed||(reuseSeed&&this.sessionSeed?this.sessionSeed:createSeed()));const difficulty=difficultyFor(this.settings.get('difficulty')),random=randomForSeed(this.sessionSeed),profile=chooseEncounterProfile(random.fork('profile'),difficulty),duration=difficulty.duration,director=new EncounterDirector(random.fork('director'),profile,difficulty,duration),routes=new FlightRouteNetwork();this.state.begin(mode);const context={scene:this.scene,camera:this.camera,input:this.input,settings:this.settings,world:this.world,events:this.events,fog:this.fog,assets:this.assets,audio:this.audio,onboarding:this.onboarding,seed:this.sessionSeed,difficulty,random,routes,director,onEnd:(result)=>this.endRun({...result,seed:this.sessionSeed,difficulty:difficulty.name})};this.mode=mode==='bat'?new BatMode({...context,hud:this.batHUD}):new SnakeMode({...context,hud:this.snakeHUD});this.input.requestLock();this.toast(`${profile.name} · ${this.sessionSeed}`);}
  endRun(result){this.state.setPhase(GamePhase.ENDED);this.input.releaseLock();this.audio?.endTransition(result.success);this.endScreen.show({...result,mode:this.state.mode});}
  restart(sameSeed=true){const mode=this.state.mode;if(mode)this.startMode(mode,sameSeed);}
  switchMode(){const mode=this.state.mode==='bat'?'snake':'bat';if(mode&&this.sessionSeed)this.startMode(mode,true,this.sessionSeed);}
  returnToMenu(){this.disposeMode();this.state.setPhase(GamePhase.MENU);this.state.mode=null;this.input.releaseLock();this.endScreen.hide();this.pauseScreen.classList.add('hidden');this.mainMenu.show();this.fog.setThermal(false);this.camera.fov=72;this.camera.updateProjectionMatrix();}
  pause(){if(!this.state.isPlaying())return;this.state.setPhase(GamePhase.PAUSED);this.pauseScreen.classList.remove('hidden');}
  resume(){if(this.state.phase!==GamePhase.PAUSED)return;this.state.setPhase(GamePhase.PLAYING);this.pauseScreen.classList.add('hidden');this.input.requestLock();}
  showNotes(){const modal=document.createElement('section');modal.className='panel-modal';modal.innerHTML='<div class="panel-sheet field-notes"><p class="eyebrow">Field notes 01</p><h2>At the flight line</h2><h3>Heat pits</h3><p>Cuban boas have temperature-sensitive facial pits that help resolve warm prey in darkness. The game exaggerates persistence and color for human players.</p><h3>Echolocation</h3><p>Cave bats emit calls and interpret returning sound. The audible calls and luminous reconstruction here are artistic translations, not literal bat perception.</p><h3>Hunting positions</h3><p>Boas have been observed hanging near cave entrances and intercepting emerging bats. Their exact coordination remains less certain than the game’s shared tactical framing.</p><h3>Emergence</h3><p>Bat departures have pulses, gaps, route choices, and collective reactions. Batsnake compresses a large colony event into a short authored encounter.</p><h3>What is simplified</h3><p>Flight, heat, acoustics, group positioning, and constriction are readable simulations—not claims of complete animal behavior. Procedural animals and generated sound remain placeholders.</p><div class="panel-footer"><button class="text-button">Close notes</button></div></div>';this.uiRoot.append(modal);modal.querySelector('button')?.addEventListener('click',()=>modal.remove());}
  disposeMode(){if(this.mode){this.mode.dispose();this.mode=null;}this.onboarding?.hide();this.batHUD?.hide();this.snakeHUD?.hide();}
  fixedUpdate(dt){if(this.state.isPlaying()){this.world.fixedUpdate();this.mode?.fixedUpdate(dt);}}
  update(dt){this.input.update();if(this.input.consumeAction('pause')){if(this.state.isPlaying())this.pause();else if(this.state.phase===GamePhase.PAUSED)this.resume();}if(this.input.consumeAction('restart')&&(this.state.isPlaying()||this.state.phase===GamePhase.ENDED))this.restart(true);if(this.state.isPlaying())this.mode?.update(dt);else if(this.state.phase===GamePhase.MENU)this.updateMenuCamera(dt);this.onboarding?.update(dt);this.dust.update(dt);this.drips.update(dt);this.impacts.update(dt,this.camera);this.ambience.update(dt,this.camera,this.mode?.director);this.audio.updateListener(this.camera);this.motion.update(dt,this.mode?.speed?.()||0);this.performance.update(dt,this.renderer,{bats:this.mode?.activeBats?.()||0,particles:this.settings.profile().particles,sensoryMs:this.mode?.sensoryTime?.()||0,renderMs:this.post.lastRenderMs,renderTargets:this.post.targetCount,seed:this.sessionSeed,phase:this.mode?.director?.phase||'menu',routes:this.mode?.flock?.routeOccupancy?.()||{},panic:this.mode?.flock?.panicCount||0,alertness:this.mode?.snakes?.alertness?.()||0,input:this.input.activeDevice,directorMs:this.mode?.director?.lastUpdateMs||0});this.input.endFrame();}
  updateMenuCamera(dt){this.menuTime+=dt;this.camera.position.set(2.6+Math.sin(this.menuTime*.1)*1.1,6.4+Math.sin(this.menuTime*.16)*.4,-27+Math.cos(this.menuTime*.08)*1.6);this.camera.lookAt(-.5,6,34);}
  render(){this.post.render();}
  applyResolution(){if(!this.renderer)return;const profile=this.settings.profile();const ratio=Math.min(2,devicePixelRatio)*profile.pixelRatio*this.settings.get('resolutionScale');this.renderer.setPixelRatio(ratio);this.renderer.setSize(innerWidth,innerHeight,false);}
  onResize(){if(!this.camera||!this.renderer)return;this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.applyResolution();this.post?.resize(innerWidth,innerHeight);}
  progress(message,value){const status=document.getElementById('loading-status'),bar=/** @type {HTMLElement|null} */(document.getElementById('load-progress'));if(status)status.textContent=message;if(bar)bar.style.width=`${value*100}%`;}
  toast(message){const element=document.getElementById('toast');if(!element)return;element.textContent=message;element.classList.add('visible');clearTimeout(this.toastTimer);this.toastTimer=window.setTimeout(()=>element.classList.remove('visible'),2800);}
}
