// @ts-check
import * as THREE from 'three';
export class ImpactEffects {
  /** @param {THREE.Scene} scene */
  constructor(scene){this.scene=scene;this.effects=[];}
  /** Local limestone fragments: deliberately no rings, outlines, or acoustic-memory activation. */
  impact(position,color=0xa7b8ae){const count=12,positions=new Float32Array(count*3),velocities=[];for(let i=0;i<count;i++){const angle=i*2.39996,spread=.18+(i%4)*.045;positions[i*3]=(i%3-1)*.018;positions[i*3+1]=0;positions[i*3+2]=((i+1)%3-1)*.018;velocities.push(new THREE.Vector3(Math.cos(angle)*spread,.12+(i%5)*.055,Math.sin(angle)*spread));}const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(positions,3));const material=new THREE.PointsMaterial({color,size:.045,transparent:true,opacity:.72,depthWrite:false,sizeAttenuation:true});const mesh=new THREE.Points(geometry,material);mesh.position.copy(position);this.scene.add(mesh);this.effects.push({mesh,velocities,life:.38,maxLife:.38,kind:'impact'});}
  /** A brief directional wake for a passing strike, visually separate from both rock dust and sonar. */
  slipstream(position,color=0xc88663){const positions=new Float32Array([-0.08,.03,-.35, .08,-.03,.35, -.04,-.06,-.28, .04,.06,.28]);const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(positions,3));const material=new THREE.LineBasicMaterial({color,transparent:true,opacity:.42,depthWrite:false});const mesh=new THREE.LineSegments(geometry,material);mesh.position.copy(position);this.scene.add(mesh);this.effects.push({mesh,velocities:[],life:.24,maxLife:.24,kind:'slipstream'});}
  update(dt,camera){for(let i=this.effects.length-1;i>=0;i--){const effect=this.effects[i];effect.life-=dt;effect.mesh.material.opacity=Math.max(0,effect.life/effect.maxLife)*(effect.kind==='impact'?.72:.42);if(effect.kind==='impact'){const attribute=effect.mesh.geometry.attributes.position;for(let p=0;p<effect.velocities.length;p++){const velocity=effect.velocities[p];attribute.setXYZ(p,attribute.getX(p)+velocity.x*dt,attribute.getY(p)+velocity.y*dt,attribute.getZ(p)+velocity.z*dt);velocity.y-=dt*.7;}attribute.needsUpdate=true;}else{effect.mesh.lookAt(camera.position);effect.mesh.scale.z+=dt*6;}if(effect.life<=0){this.scene.remove(effect.mesh);effect.mesh.geometry.dispose();effect.mesh.material.dispose();this.effects.splice(i,1);}}}
}
